### ISSUE TITLE
Consider adding a real JSON library for (extended) property_tree json output

### ISSUE THREAD

**Issue by thecodefactory** [libbitcoin/libbitcoin-system#1047]
Just ran across this one and it looks decent (API-wise, and can be included with a single include) and license compatible (MIT):

https://github.com/nlohmann/json

**Comment by evoskuil** [comment]
Is there a limitation in using the boost library for this?

**Comment by thecodefactory** [comment]
The emitted number encodings (as quoted strings) can cause some problems with existing tools (but might only matter if websocket/json-rpc is merged).  If there's a workaround for that using the boost property_trees, maybe I'm just not aware of it.

**Comment by evoskuil** [comment]
This is a feature, not a bug. JSON number cannot encode a 64 bit domain.

**Comment by thecodefactory** [comment]
Some tool I was using for testing was complaining that the JSON responses were invalid because a particular response field was expected to be a number instead of a string.  I don't recall what that was at the moment and maybe that kind of compatibility isn't a primary interest right now, but it may come up on occasion.  If it's largely imagined or unimportant, we can drop the issue, but I wanted to note it since i hit it and couldn't find a supported property_tree resolution (as far as I know there isn't one, though boost issues around it exist, or did at one point).

**Comment by evoskuil** [comment]
For lesser domains a number is fine, and for backward compat (JSON-RPC) the domain bug might be necessary to accept. It’s not clear to me that property_tree cannot support numeric (unquoted) properties. I’d like to avaid another dependency for this.

**Comment by thecodefactory** [comment]
According to boost issues filed about it, they're aware of the issue:

https://svn.boost.org/trac10/ticket/9721
https://svn.boost.org/trac10/ticket/9496
https://svn.boost.org/trac10/ticket/6351

The post process is suggested as one of the commonly used work-arounds, but it can be quite expensive performance-wise.

**Comment by thecodefactory** [comment]
Also, to weigh it, the linked dependency is a single header file, no libs (as far as I can tell).  Doesn't make it any less an external dependency, but a bit easier to work with.  I'm ok keeping boost formatting as-is for now, but for compatibility reasons and projects that build on later, we may need proper json output.  If boost's property tree is interested in providing that, it would be ideal, but it seems like that's not the intended use and/or it may not happen since it's an old issue at this point.

**Comment by vdeurzen** [comment]
nlohmann's JSON library is very nice. I've used it in several projects and am quite impressed with it so far. If you are looking for someone to add this, I'll be happy to give it a try.

**Comment by evoskuil** [comment]
Just looked quickly, but looks perfect. Would want to embed. MIT License is easy. Thanks!

**Comment by evoskuil** [comment]
Will drop boost.ptree and implement streaming parser build in boost.json.

**Comment by evoskuil** [comment]
This is implemented in pending pull request, using boost.json.
