### ISSUE TITLE
Remove uncompleted bip39 wordlists. 

### ISSUE THREAD

**Issue by ldz1** [libbitcoin/libbitcoin-system#1074]
Libbitcoin cointains uk, cs and ru word lists that are actually not the official bip39 word lists. They are still in progress / in preparation. I think it is bad idea to offer possibly incorrect lists. I suggest deleting them and wait until they are prepared.

Example (ukrainian):
https://github.com/bitcoin/bips/pull/442

The official lists:
https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by thecodefactory** [comment]
I don't think having them in strictly hurts anything, as most people using "unsupported" word lists will be doing so intentionally (i.e. it won't be compatible elsewhere).  Changing them will though, if people are using them.  We could either remove them, or more aggressively update them to track the latest.

**Comment by evoskuil** [comment]
I'd agree with removing these if they are not finalized by the time we release v4.

**Comment by evoskuil** [comment]
Done?
