### ISSUE TITLE
License in COPYING file is inconsistant with README

### ISSUE THREAD

**Issue by jameshilliard** [libbitcoin/libbitcoin-system#1101]
The README indicates the project license is Lesser AGPLv3 while the [COPYING](https://github.com/libbitcoin/libbitcoin-system/blob/master/COPYING) file indicates normal AGPLv3.

**Comment by evoskuil** [comment]
The reference to a “lesser clause” is not a change to LGPL but to the modification that is presented at the top of the readme.

**Comment by jameshilliard** [comment]
ah, I see, I was assuming it was similar to how there is a GPLv3 and LGPLv3

**Comment by evoskuil** [comment]
No worries, the reader language can be improved.
