### ISSUE TITLE
How i can get correct SHA256 hash of  P2PKH script ?

### ISSUE THREAD

**Issue by mousemove** [libbitcoin/libbitcoin-system#1102]
Hello guys!
I need correct create  SHA256 hash of  P2PKH script
for example:
Address:1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa
P2PKH script:76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac (OR "dup hash160 [62e907b15cbf27d5425399ebf6f0fb50ebb88f18] equalverify checksig")
SHA256 hash: 6191c3b590bfcfa0475e877c302da1e323497acf3b42c08d8fa28e364edf018b

I use this:
```
    payment_address destination("1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa");
    script outputScript = script().to_pay_key_hash_pattern(destination.hash());
   std::string = outputScript.to_string(0);
```

and get correct p2kh code

But, how i can get correct SHA256 hash after this move? Try to use 
`encode_hash( sha256_hash(outputScript.to_data(true)))`
or use algrotithm sha256 to string 62e907b15cbf27d5425399ebf6f0fb50ebb88f18/ 76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac  dup hash160 [62e907b15cbf27d5425399ebf6f0fb50ebb88f18] equalverify checksig

and no can create correct SHA256 hash of  P2PKH script

Please direct me to correct use. In examples, i need  receive "6191c3b590bfcfa0475e877c302da1e323497acf3b42c08d8fa28e364edf018b"

Sorry for my english

**Comment by evoskuil** [comment]
You probably want: outputScript.to_data(false)

Why are you taking a single sha_256 of the script?
