### ISSUE TITLE
Runtime error in validate_localization (Visual Studio 2017 x64 build WITH_ICU)

### ISSUE THREAD

**Issue by BrodaUa** [libbitcoin/libbitcoin-system#1104]
Hello,

I was trying to use the libbitcoin-explorer _mnemonic-to-seed_ function in my application. But, as I understood, since the whole project is aimed to be used as a console tool, I ended up reimplementing _mnemonic-to-seed_ function logic myself, using only libbitcoin-system. 

I am using the example project, provided in source code. The host machine is WinServer 2016 Datacenter x64 (eventually it is Data Science Virtual Machine in Azure). My app:

**main.cpp**

```
#include <cstdlib>
#include <string>
#include <bitcoin/system.hpp>
#include "test.h"


BC_USE_LIBBITCOIN_MAIN


int bc::system::main(int argc, char* argv[])
{
	unsigned char arr[64];
	unsigned char *data = (unsigned char *)"GG";
	test(data, 2, arr);
	return 0;
}
```

**test.h**

```
#pragma once


#ifdef _WIN32
#ifdef __cplusplus
extern "C"
#endif
#endif
void
#ifdef _WIN32
__stdcall
#endif
test(
	unsigned char	*pData,
	unsigned int	uLen,		
	unsigned char	Hash[16]);
```

**test.cpp**

```
#include "test.h"

#include <string>
#include <vector>
#include <bitcoin/system.hpp>

using namespace bc::system;
using namespace bc::system::config;
using namespace bc::system::wallet;

void
#ifdef _WIN32
__stdcall
#endif
test(
	unsigned char	*pData,
	unsigned int	uLen,		
	unsigned char	Hash[64])
{
	std::cout << "enter\n";
	const std::vector<std::string> words = { "health", "boil", "host",
									"ostrich", "fire", "spike",
									 "body", "solar", "collect",
									 "harvest", "catalog", "cup",
									 "mix" ,"tattoo" ,"merge" };
	std::string passphrase = "passphrase";
	passphrase += (char *)pData;

	std::cout << "start decode\n";
	const auto seed = decode_mnemonic(words, passphrase);
	std::cout << "end decode\n";

	strcpy((char*)Hash, "");
	std::cout << "exiting\n";
}
```

When I build the project with **WITH_ICU** flag and run it, getting the **Runtime error** raised in _validate_localization_ ; _unicode.cpp_. As it says there are checking for dependencies, how it could be resolved?

**Comment by evoskuil** [comment]
Use bc::system::cout in place of std::cout, as required in vc++ (along with bc::system::main(...)).

**Comment by thecodefactory** [comment]
@BrodaUa See https://github.com/libbitcoin/libbitcoin-system/issues/1029 for some relevant details.

**Comment by evoskuil** [comment]
Resolved: https://github.com/libbitcoin/libbitcoin-system/pull/1155
