### ISSUE TITLE
build with boost 1.70.0 (OSX)

### ISSUE THREAD

**Issue by 0xdead4ead** [libbitcoin/libbitcoin-system#1111]
Hello!
In install.sh script I replaced the following lines:
```
BOOST_URL="http://downloads.sourceforge.net/project/boost/boost/1.70.0/boost_1_70_0.tar.bz2"
BOOST_ARCHIVE="boost_1_70_0.tar.bz2"
...
BOOST_OPTIONS=""
```

Insert to terminal:
`./install.sh --with-icu --with-png --with-qrencode --build-icu --build-zlib --build-png --build-qrencode --build-boost`

Script interrupted on build boost. It is output:

> error: Name clash for '<p/usr/local/lib>libboost_chrono.dylib'
> error: 
> error: Tried to build the target twice, with property sets having 
> error: these incompatible properties:
> error: 
> error:     -  none
> error:     -  `<dll-path>/usr/local/bin <linkflags>-L/usr/local/lib`
> error: 
> error: Please make sure to have consistent requirements for these 
> error: properties everywhere in your project, especially for install
> error: targets.

If I want to build boost and libbitcoin at the same time, what should I do?

**Comment by thecodefactory** [comment]
`install.sh` is used for building the supported dependencies, including boost.  What happens if you don't modify the `install.sh` script?  Boost 1.70.0 is not the supported version, so clearing all of the required options and using a different version may result in errors.

**Comment by thecodefactory** [comment]
`./install.sh --with-icu --with-png --with-qrencode --build-icu --build-zlib --build-png --build-qrencode --build-boost`

@0xdead4ead It also appears that you're not using a prefix, which is trying to overwrite system libraries.  That's not recommended.  I suggest using something like this (after reverting the `install.sh` script back to an unmodified state):

`./install.sh --with-prefix=$HOME/libbitcoin --with-icu --with-png --with-qrencode --build-icu --build-zlib --build-png --build-qrencode --build-boost`

**Comment by 0xdead4ead** [comment]
Boost 1.69, given the changes above, is success. The error don't your repository. The question is closed. Thanks for the answer!
