### ISSUE TITLE
regarding P2WPKH spend transaction

### ISSUE THREAD

**Issue by bidelakbari** [libbitcoin/libbitcoin-system#1112]
I managed to build transactions that spend both P2PKH and P2WPKH-P2SH but when I try to build the transaction for native P2WPKH spend, the transaction errors upon pushing to the network and complains for the signature

my question is does <code>script().create_endorsement</code> needs to be somehow changed to support spending P2WPKH outputs?

**Comment by bidelakbari** [comment]
replyin to my own issue
yes It can be uses. I just needed to generate the output script myself

**Comment by evoskuil** [comment]
Thanks, we should have full support eventually.
