### ISSUE TITLE
Coveralls is not working.

### ISSUE THREAD

**Issue by ldz1** [libbitcoin/libbitcoin-system#1120]
Renaming of libbitcoin to libbitcoin-system caused coverall to stop working.

**Comment by ldz1** [comment]
The new coveralls was created by @pmienk. 
https://coveralls.io/github/libbitcoin/libbitcoin-system

Coverall status fix in README.md:
https://github.com/libbitcoin/libbitcoin-system/pull/1121

**Comment by evoskuil** [comment]
Complete?

**Comment by ldz1** [comment]
@evoskuil: I hope so. I suppose @pmienk can say more about it.

**Comment by evoskuil** [comment]
@pmienk ping
