### ISSUE TITLE
Compiling on MacOS Undefined symbols

### ISSUE THREAD

**Issue by Klaud2699** [libbitcoin/libbitcoin-system#1123]
Installing from pkges

brew tap cuber/homebrew-libsecp256k1
brew install libsecp256k1
brew install libbitcoin

g++ --std=c++11 -o main main.cpp 

Undefined symbols for architecture x86_64:
  "libbitcoin::config::checkpoint::checkpoint(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)", referenced from:
      ___cxx_global_var_init in main-79cb22.o
      ___cxx_global_var_init.1 in main-79cb22.o
      ___cxx_global_var_init.3 in main-79cb22.o
      ___cxx_global_var_init.5 in main-79cb22.o
      ___cxx_global_var_init.7 in main-79cb22.o
      ___cxx_global_var_init.9 in main-79cb22.o
      ___cxx_global_var_init.11 in main-79cb22.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build] Error 1

Try build from source too from README.md, it doesnt help

**Comment by evoskuil** [comment]
I don’t believe those packages are current or maintained. Should prob be dropped from the docs. Have you tried building using the installer? That’s current and maintained/tested.

**Comment by evoskuil** [comment]
Thanks for reporting. I've removed the readme ref for these outdated packages. Please let us know if you have a problem with the `install.sh` build.

**Comment by evoskuil** [comment]
BTW, I only found these references on the version2 readme.md, are you building from production (version3) or master?

**Comment by Klaud2699** [comment]
I try to build from master, also build script work.
But u miss to add one more dependencies lib gmp, pls add full dependencies list,exmaple:
boost 1.57+
gmp
libbitcoin/secp256k1

Can u add options to add libbitcoin-system via git submodule, and build it via cmake?

**Comment by evoskuil** [comment]
GMP is not a dependency. All are listed.
