### ISSUE TITLE
Block locator size unit test failure.

### ISSUE THREAD

**Issue by verbus** [libbitcoin/libbitcoin-system#1124]
```
make  check-TESTS
make[1]: Entering directory '/home/verbus/build-libbitcoin/libbitcoin'
make[2]: Entering directory '/home/verbus/build-libbitcoin/libbitcoin'
FAIL: libbitcoin-test_runner.sh
========================================
   libbitcoin 3.4.0: ./test-suite.log
========================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: libbitcoin-test_runner.sh
===============================

FAIL libbitcoin-test_runner.sh (exit status: 201)

============================================================================
Testsuite summary for libbitcoin 3.4.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to eric@voskuil.org
============================================================================
make[2]: *** [Makefile:6032: test-suite.log] Error 1
make[2]: Leaving directory '/home/verbus/build-libbitcoin/libbitcoin'
make[1]: *** [Makefile:6140: check-TESTS] Error 2
make[1]: Leaving directory '/home/verbus/build-libbitcoin/libbitcoin'
make: *** [Makefile:6347: check-am] Error 2
Running 1901 test cases...
Platform: linux
Compiler: GNU C++ version 9.1.0
STL     : GNU libstdc++ version 20190503
Boost   : 1.62.0
test/chain/block.cpp(71): fatal error: in "chain_block_tests/block__locator_size__positive_backoff__returns_log_plus_eleven": critical check 18u == chain::block::locator_size(top) has failed [18 != 19]

real	13m15.612s
user	41m36.402s
sys	3m6.667s
```

**Comment by evoskuil** [comment]
This is likely due to differences in the underlying rounding behavior.

**Comment by thecodefactory** [comment]
@verbus Can you provide some more details on this?  I've compiled and run the tests from current `master` using gcc/g++ 9.1.0 on GNU/Linux (debian) and cannot reproduce this failure.  Is there anything in particular that you know of that is causing this?

I realize that you're running `version3`, so I also tried that, but did not see this issue there either.

**Comment by narodnik** [comment]
I have the same error also:
```
$ ./test/libbitcoin-system-test 
Running 1710 test cases...
test/chain/block.cpp(67): fatal error: in "chain_block_tests/block__locator_size__positive_backoff__returns_log_plus_eleven": critical check chain::block::locator_size(top) == 18u has failed [19 != 18]

*** 1 failure is detected in the test module "libbitcoin_test"
```

**Comment by thecodefactory** [comment]
@narodnik Hrm, interesting. Any ideas on the cause?  Perhaps not related to gcc/g++ version 9?

```
$ ./test/libbitcoin-system-test 
Running 2107 test cases...

*** No errors detected

$ grep "gcc" Makefile
CC = gcc-9
CCDEPMODE = depmode=gcc3
CXXDEPMODE = depmode=gcc3
PTHREAD_CC = gcc-9
ac_ct_CC = gcc-9

$ grep "g++" Makefile
CXX = g++-9
CXXCPP = g++-9 -E
```

**Comment by evoskuil** [comment]
It’s most likely the rounding function for the log() output (see above).

**Comment by thecodefactory** [comment]
Will try to get an Ubuntu 19 VM setup to test this out as @youssefnotes reported in #63

**Comment by thecodefactory** [comment]
@evoskuil Just got around to looking into this and am able to reproduce easily on an Ubuntu 19 VM.  It's the rounding function as you suggested.  Do you have some context on what the required rounding is?  If it's a matter of consistency only, there's 2 things: 1) According to [this](https://en.cppreference.com/w/cpp/numeric/fenv/FE_round), "rounding is only guaranteed if #pragma STDC FENV_ACCESS ON is set", which I don't see set ... but it seemingly makes no difference if that is set or not (at least using gcc in my test envs) because I'm also seeing the compiler warning of `ignoring #pragma STD FENV_ACCESS [-Wunknown-pragmas]`.  2) What does enable the rounding to work is replacing the round of `FE_UPWARD` to either `FE_TONEAREST` or `FE_TOWARDZERO`.

Either of these rounds appear to work in my _normal_ dev environment, as well as the Ubuntu VM without further unit test changes.  Preference for either?

**Comment by evoskuil** [comment]
I’d say it must be rounding because it’s the only thing that can vary.

**Comment by evoskuil** [comment]
@thecodefactory please verify this change, I cannot reproduce with or without the change.

**Comment by thecodefactory** [comment]
@evoskuil The unit test looks good in the Ubuntu VM as well as my normal setup.

**Comment by evoskuil** [comment]
Thanks, ridiculous how simple this was :/

**Comment by Sjors** [comment]
I get hit by this error on a fresh Google App Engine Ubuntu installation, when using the automatic install script: https://github.com/libbitcoin/libbitcoin-system#debianubuntu

**Comment by evoskuil** [comment]
Hi Sjors, which version of Libbitcoin?

**Comment by Sjors** [comment]
The default fetched by the install script, so I think 3.6.0. `build-libbitcoin-server/libbitcoin` is at `commit 52f24693f8bdd4c79d66839d90132179f486e7d8 (grafted, HEAD -> version3, tag: v3.6.0, origin/version3)`

**Comment by evoskuil** [comment]
You can ignore the test failure, maybe back-port the fix from master.

**Comment by Sjors** [comment]
Unfortunately `./install.sh --disable-tests` doesn't actually skip that test, so I end up without the `bs` executable.

**Comment by evoskuil** [comment]
It should disable all tests.

**Comment by thecodefactory** [comment]
> You can ignore the test failure, maybe back-port the fix from master.

The fix is backported from `master`: https://github.com/libbitcoin/libbitcoin-system/pull/1166
