### ISSUE TITLE
Pedersen Commitment Example

### ISSUE THREAD

**Issue by ryandeng1** [libbitcoin/libbitcoin-system#1135]
I am trying to run the Pedersen commitment example in the wiki but I get the error: "error: ‘ec_sum’ was not declared in this scope". I installed using the install.sh script and compiled with: "g++ -std=c++11 -o commit commit.cpp $(pkg-config --cflags --libs libbitcoin)". I also set my PKG_CONFIG_PATH to the prefix that I installed bitcoin with.

**Comment by thecodefactory** [comment]
@ryandeng1 What version (master or version3, for example)?  Also, can you provide some more context, from the command line?  Just not sure where to start on this.

**Comment by ryandeng1** [comment]
g++ -std=c++11 -o commit commit.cpp $(pkg-config --cflags --libs libbitcoin) -lgmp

I am using version 3 I believe.

**Comment by thecodefactory** [comment]
@ryandeng1 Ah, ok I see the issue.  The first sentence in the Pederson Committments in EC Form doc (https://github.com/libbitcoin/libbitcoin-system/wiki/Pedersen-Commitments-in-EC-Form) indicates that ec_sum is only available in version 4 of libbitcoin.  It may be confusing because version 4 is not released yet and is not production.  If you build from the `master` branch, that method will be available.  `version3` does not include it.

By context, I had just meant that a cut and paste snippet could have been useful to help identify the issue, but I think that's no longer needed.

**Comment by evoskuil** [comment]
Probably need `bc::system::` vs `bc::`.

**Comment by ryandeng1** [comment]
@evoskuil  Could you elaborate on that point? Do you mean in the statement "using namespace bc;"?

@thecodefactory  I tried building from the master, but then the compiler errors and says:
"pedersen.cpp:1:10: fatal error: bitcoin/bitcoin.hpp: No such file or directory
 #include <bitcoin/bitcoin.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
"

I took a look at the installed directory and instead of bitcoin.hpp it has system.hpp.

**Comment by thecodefactory** [comment]
@ryandeng1 version4 renamed bitcoin.hpp to system.hpp.  You can't have a mixed install directory though, as that can cause issues.  Try installing version4/master to a new prefix directory and update your PKG_CONFIG_PATH.

**Comment by ryandeng1** [comment]
I reintalled it in a new prefix directory and updated PKG_CONFIG_PATH but I have the same issues. Just to be clear, I am supposed to change the header to "include <bitcoin/system.hpp>" right? Otherwise, it doesn't even recognize bitcoin/bitcoin.hpp. I also deleted the old prefix directory to be safe.

**Comment by thecodefactory** [comment]
@ryandeng1 Ok, try this instead:

```
g++ -std=c++11 -o commit commit.cpp $(pkg-config --cflags --libs --static libbitcoin-system)
```

Pkg-config requires the updated name as well -- sorry I missed that before.

**Comment by thecodefactory** [comment]
@ryandeng1 Any updates here?

**Comment by ryandeng1** [comment]
Sorry for the late reply, yes it currently works! Thanks so much. I'll close this issue for now.
