### ISSUE TITLE
Fatal error while compiling src/math/elliptic_curve.cpp - no secp256k1.h

### ISSUE THREAD

**Issue by bvrulez** [libbitcoin/libbitcoin-system#1138]
I am installing `libbitcoin-system` `v3.6.0` with `autotool` and get the following error:

```
  CXX      src/math/libbitcoin_la-crypto.lo
  CXX      src/math/libbitcoin_la-elliptic_curve.lo
src/math/elliptic_curve.cpp:23:10: fatal error: secp256k1.h: No such file or directory
 #include <secp256k1.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

I already installed `libbitcoin/secp256k1`. 

My `src` contains
```
-rw-r--r--  1 pi pi   1725 Sep  4 07:11 checksum.cpp
-rw-r--r--  1 pi pi   1510 Sep  4 07:11 crypto.cpp
drwxr-xr-x  2 pi pi   4096 Sep  4 11:18 .deps
-rw-r--r--  1 pi pi      0 Sep  4 11:17 .dirstamp
-rw-r--r--  1 pi pi  12844 Sep  4 07:11 elliptic_curve.cpp
drwxr-xr-x  3 pi pi   4096 Sep  4 10:36 external
-rw-r--r--  1 pi pi   4277 Sep  4 07:11 hash.cpp
-rw-r--r--  1 pi pi    342 Sep  4 11:18 libbitcoin_la-checksum.lo
-rw-r--r--  1 pi pi 270048 Sep  4 11:18 libbitcoin_la-checksum.o
-rw-r--r--  1 pi pi    336 Sep  4 11:18 libbitcoin_la-crypto.lo
-rw-r--r--  1 pi pi 186588 Sep  4 11:18 libbitcoin_la-crypto.o
drwxr-xr-x  2 pi pi   4096 Sep  4 11:18 .libs
-rw-r--r--  1 pi pi   2015 Sep  4 07:11 secp256k1_initializer.cpp
-rw-r--r--  1 pi pi   2712 Sep  4 07:11 secp256k1_initializer.hpp
-rw-r--r--  1 pi pi   7349 Sep  4 07:11 stealth.cpp
```

I am doing this on a Raspberry Pi 3B with Raspian Buster. 

EDIT: I am new to this. I figured I could just download the file (and the recovery) from [here](https://github.com/libbitcoin/secp256k1/tree/master/include). But where do I have to put it?

**Comment by thecodefactory** [comment]
@bvrulez The recommended way to build libbitcoin (including all required dependencies) is with the `install.sh` script.  An example invocation is here: https://github.com/libbitcoin/libbitcoin-system#building-icu-zlib-png-qrencode-andor-boost

**Comment by thecodefactory** [comment]
> EDIT: I am new to this. I figured I could just download the file (and the recovery) from here. But where do I have to put it?

If the secp256k1 repository was built and installed in a system directory, it should be found by the configure script.  This isn't the recommended way to install though, as it's cleaner to install to a user prefix directory rather than requiring root write access.

**Comment by bvrulez** [comment]
I solved this issue by installing `libsecp256k1-dev` via `apt`. I don't know if I put the files in a system directory by using `sudo`. The configure script did not mention that it did not find secp256k1, it just came up during `make`. I wanted to install just `libbitcoin-system` instead of the whole thing because it is just a Raspberry that is already running a full node from `core`. Thanks for answering!

**Comment by thecodefactory** [comment]
Ok, `make` would not be able to find the header unless it was in a system directory.  Sounds like you may not have installed it manually, but that `apt` took care of it.  It's worth noting that the version installed via `apt` isn't the exact version installed from our installer script, so it's possible at some unspecified point in the future that may no longer work, but for now, you should be good to go.

Even on a raspberry pi, I still recommend installing with the proper dependencies :-)

**Comment by bvrulez** [comment]
To be clear again also for my learning: I installed `libbitcoin-secp256k1`  from source, but maybe I did use `sudo` and it went into a system folder. Then I did `./autogen.sh` and `./configure` for `libbitcoin-system` and it all went fine until `make` did not find the header. Then I installed `secp256k1-dev` via `apt`. Now it works. I would think that `./configure` should already mention that there are missing files.

**Comment by bvrulez** [comment]
Actually, it did not work. `make` went further than the last time but not exited with:

 ```
 CXXLD    src/libbitcoin.la
copying selected object files to avoid basename conflicts...
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    examples/libbitcoin-examples
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ec_pubkey_create'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ec_pubkey_tweak_mul'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ec_pubkey_serialize'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_sign'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_sign_recoverable'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ec_privkey_tweak_mul'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_serialize_compact'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_signature_serialize_der'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_context_destroy'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_signature_normalize'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ec_pubkey_tweak_add'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ec_pubkey_parse'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_signature_parse_compact'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_signature_parse_der'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_verify'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_parse_compact'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ec_seckey_verify'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_context_create'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_nonce_function_rfc6979'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recover'
/usr/bin/ld: src/.libs/libbitcoin.so: undefined reference to `secp256k1_ec_privkey_tweak_add'
collect2: error: ld returned 1 exit status
make: *** [Makefile:2419: examples/libbitcoin-examples] Error 1
```

**Comment by thecodefactory** [comment]
In this case, it looks like the headers were found, but the libraries are not being found.  You can either manually locate the system installed libraries and update your `LDFLAGS` before building, or give the `install.sh` script a go.
