### ISSUE TITLE
Incorrect and inconsistent wordlist rejection

### ISSUE THREAD

**Issue by Raveen87** [libbitcoin/libbitcoin-system#1146]
Hi!

I'm having some issues when trying to generate a HD-seed from the English wordlist.
The error message I'm getting is that the words are not valid. But the words are from the BIP39 English wordlist.
And I'm also able to use those words if I change up the combination:

```
$ bx mnemonic-to-seed --language en abandon abandon abandon
The specified words are not a valid mnemonic in the specified dictionary.

$ bx mnemonic-to-seed --language en about about about
The specified words are not a valid mnemonic in the specified dictionary.

$ bx mnemonic-to-seed --language en above above above
The specified words are not a valid mnemonic in the specified dictionary.

$ bx mnemonic-to-seed --language en able able able
0d11269ccbb4d746a15888cbf45e8ff3ab0d159b06c36db56dd9bc82702077b56279209979e3a9cfe21825507f15dbb7cf5b00e0b716af8975b14221747d6856

$ bx mnemonic-to-seed --language en abandon about above
d43140d4db6b0d23eb546f60cfe5c221c50159836395b38148364fa2eadfb474fc270c8af7181146d76a1fb5f4b9436042f406fe9b2cc821ba22e29b53bbb990

$ bx mnemonic-to-seed --language en above above abandon
84b2328d5deda652bdcce534ddfaeb0ea6abc0476ada9bb9688cb1a286397a5fbad97d59b92e056079df1982e1d8cf8ffaa74257bb7317feca735521a9d0a47f

$ bx mnemonic-to-seed --language en about abandon above
The specified words are not a valid mnemonic in the specified dictionary.
```

I'm using version 3.6.0.

**Comment by evoskuil** [comment]
This appears to be a conflict resulting from the use of the word "abandon" in both the en and fr dictionaries.

**Comment by Raveen87** [comment]
> This appears to be a conflict resulting from the use of the word "abandon" in both the en and fr dictionaries.

Even though just using `above` or `about` also produces the same error?

**Comment by evoskuil** [comment]
Try it without language specification.

**Comment by Raveen87** [comment]
> Try it without language specification.

Same input:

```
$ bx mnemonic-to-seed abandon abandon abandon
d7d26a9d0e4b7a2728216a2897481449d02653b9079bbfd5551f82da21a6710dbf763cea70d68cbf5ba614c15b29690315c5c2163488b2e838875af7a6a4a811

$ bx mnemonic-to-seed about about about
WARNING: The specified words are not a valid mnemonic in any supported dictionary.
13a7d85ea53dc980a846dbfd572deb63b54a0f2bd578bffa24f416185d309b203e84c56b4b069fd69f831408b1e89a19c8f4646c7cb0adcc610d97f939c37d15

$ bx mnemonic-to-seed above above above
WARNING: The specified words are not a valid mnemonic in any supported dictionary.
e067694d53e251de2574fe7832fe0f7958013af23c8028a1c86c545ba0b1c3c2394eb8e760f856145340864cd87df80d8f279daa7d8ac3bbaf9a9facca671519

$ bx mnemonic-to-seed able able able
0d11269ccbb4d746a15888cbf45e8ff3ab0d159b06c36db56dd9bc82702077b56279209979e3a9cfe21825507f15dbb7cf5b00e0b716af8975b14221747d6856

$ bx mnemonic-to-seed abandon about above
d43140d4db6b0d23eb546f60cfe5c221c50159836395b38148364fa2eadfb474fc270c8af7181146d76a1fb5f4b9436042f406fe9b2cc821ba22e29b53bbb990

$ bx mnemonic-to-seed above above abandon
84b2328d5deda652bdcce534ddfaeb0ea6abc0476ada9bb9688cb1a286397a5fbad97d59b92e056079df1982e1d8cf8ffaa74257bb7317feca735521a9d0a47f

$ bx mnemonic-to-seed about abandon above
WARNING: The specified words are not a valid mnemonic in any supported dictionary.
0c93aeae2fba009d7342e44181505b3276193fa8f75aa941f67a7db7729da667fc8ee12bedfd4e04d9f261f5805111d23f8778572a0d62c414e4ea26f3131818
```

So, same behavior except that `abandon abandon abandon` now also works.

**Comment by evoskuil** [comment]
Not the same behavior.

**Comment by evoskuil** [comment]
It appears that the en dictionary is not being located.

**Comment by evoskuil** [comment]
Given the extensive unit test coverage in libbitcoin-explorer (and libbitcoin-system), in all languages and in automatic language selection, this is most likely a bx parsing/parameterization issue.

**Comment by Raveen87** [comment]
> Given the extensive unit test coverage in libbitcoin-explorer (and libbitcoin-system), in all languages and in automatic language selection, this is most likely a bx parsing/parameterization issue.

Meaning what? Could I've done something wrong during compile/installation or be running it in a weird environment or something?

**Comment by evoskuil** [comment]
No, not your issue.

**Comment by evoskuil** [comment]
bx is a thin command line and config file parsing layer over the libbitcoin-explorer library. The library is extensively tested but the command layer is not.

**Comment by Raveen87** [comment]
I've been reading up about BIP39, and learned that the last word is supposed to be a checksum. And since I was just trying out words, it's very likely that I didn't enter the correct last word.

I tried out the same combinations I posted here earlier on https://iancoleman.io/bip39/ and the result is not entirely the same though, `abandon abandon abandon` is also rejected there. But maybe that's related to abandon being an edge-case since it consists of only zeroes, I don't know.

So maybe this is more an issue of giving a better error message?

**Comment by evoskuil** [comment]
No, it’s a bug in en language selection.

**Comment by thecodefactory** [comment]
Chiming in here after looking at it a bit.  It appears that the failure is correct -- the mnemonic is invalid in english, so specifying the dictionary displays the correct error.  The bug is that we check other dictionaries (if no language is specified) after that failure, and happen to find one that matches in some cases, which is incorrect behaviour.  It seems we may need to always require a language specification, rather than checking all (perhaps with english being the default if not specified?).

**Comment by thecodefactory** [comment]
I suspect there's a related bug in that when we validate a mnemonic, we re-create the original entropy used including the checksum, but then truncate the checksum out, which at the moment appears problematic since it seems that is used during mnemonic creation.  I need to look into that a bit more though/test/etc.

**Comment by evoskuil** [comment]
Bump

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-explorer/issues/688

**Comment by evoskuil** [comment]
This is a [bx issue](https://github.com/libbitcoin/libbitcoin-explorer/issues/688), so closing here.
