### ISSUE TITLE
Failure to build other libbitcoin libraries. Since <bitcoin/system.hpp> can't be found.

### ISSUE THREAD

**Issue by UsersDoProgram** [libbitcoin/libbitcoin-system#1154]
I'm on Ubuntu and I installed libbitcoin-system from the master yet when I try to install the blockchain or protocol libraries, autogen.sh and configure commands run quite well but once I get to running the make command it fails saying,   
"
CXX      src/src_libbitcoin_blockchain_la-block_chain_initializer.lo
In file included from src/block_chain_initializer.cpp:22:0:
./include/bitcoin/blockchain/block_chain_initializer.hpp:30:10: fatal error: bitcoin/system.hpp: No such file or directory
 #include <bitcoin/system.hpp>
          ^~~~~~~~~~~~~~~~~~~~
"
What can I do to solve this problem and successfully build the other libbitcoin libraries?

**Comment by ldz1** [comment]
Is there something against using the install.sh script for each repository? 
https://github.com/libbitcoin/libbitcoin-system#debianubuntu

**Comment by evoskuil** [comment]
Each repo install.sh installs *all* dependent libs. If you want the ful client stack install bx and if you want the full server stack instal bs.

the base library is now libbitcoin-system, renamed from libbitcoin about a year ago. Not sure why you would have the dated reference.

**Comment by UsersDoProgram** [comment]
@ldz1 for some reason it wasn't detecting secp256k1 when I used install.sh but I managed to reinstall after cleaning the failed install and everything works well.
