### ISSUE TITLE
Fetch commands do not work

### ISSUE THREAD

**Issue by ufocomp** [libbitcoin/libbitcoin-system#1156]
This do not work:

`bx fetch-balance a0e0be1350a3d3eaa3f381e3aa78f64d16e712c1bfffc7d7ca3b9b5f7409adf8`
`object does not exist`

`bx fetch-block`
`object does not exist`

`bx fetch-history a0e0be1350a3d3eaa3f381e3aa78f64d16e712c1bfffc7d7ca3b9b5f7409adf8`
`object does not exist`

This work:
`bx fetch-height`
`602021`

Settings:
`bx settings`
`settings
{
    network
    {
        channel_handshake_seconds 30
        connect_retries 0
        connect_timeout_seconds 5
        debug_file debug.log
        error_file error.log
        hosts_file hosts.cache
        identifier 3652501241
        seeds mainnet1.libbitcoin.net:8333,mainnet2.libbitcoin.net:8333,mainnet3.libbitcoin.net:8333,mainnet4.libbitcoin.net:8333
    }
    server
    {
        block_url tcp://mainnet.libbitcoin.net:9093
        client_private_key 0000000000000000000000000000000000000000
        connect_retries 0
        connect_timeout_seconds 5
        server_public_key 0000000000000000000000000000000000000000
        socks_proxy 0.0.0.0
        transaction_url tcp://mainnet.libbitcoin.net:9094
        url tcp://mainnet.libbitcoin.net:9091
    }
    wallet
    {
        hd_public_version 76067358
        hd_secret_version 76066276
        pay_to_public_key_hash_version 0
        pay_to_script_hash_version 5
        rule_fork_flags 4294967295
        transaction_version 1
        wif_version 128
    }
}`

**Comment by evoskuil** [comment]
See bx
