### ISSUE TITLE
Generic vector std::ostream operator causing compile conflict with external library

### ISSUE THREAD

**Issue by narodnik** [libbitcoin/libbitcoin-system#1159]
Using pybind11, I am unable to create bindings for any std::map<X, std::vector<Y>> ... I get tons of errors. But when I comment this function in collection.hpp everything is fine:

```
namespace std {

template <class Type>
std::ostream& operator<<(std::ostream& output, const std::vector<Type>& list);

}
```

Anything we can do to get rid of this? It seems dangerously generic and reaches outside the libbitcoin namespace.

**Comment by narodnik** [comment]
Here is the pybind11 file I'm using:
```
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>

struct foo
{
    int x;
};

PYBIND11_MAKE_OPAQUE(std::map<int, std::vector<foo>>);

PYBIND11_MODULE(wallet, m)
{
    pybind11::bind_map<std::map<int, std::vector<foo>>>(m, "foo");
}

```
Including the libbitcoin header anywhere in that file will cause the errors.

I compile it with:
```g++ -ggdb -shared -fPIC $(python3 -m pybind11 --includes) wallet.cpp -o wallet$(python3-config --extension-suffix) -std=c++2a -fconcepts $(pkg-config --cflags --libs libbitcoin-client)
```

pybind11 is a header only library, so you just copy include/pybind11 from the repo to your system headers directory. Also you need to run `pip3 install --user pybind11` and the compile command will work.

**Comment by evoskuil** [comment]
Possibly, but there are some cases where you need to extend `std`. Will have to compile the full stack to see what needs it and why.

**Comment by evoskuil** [comment]
Bumping myself on this.

**Comment by evoskuil** [comment]
This was just serialization for boost test compares. Moved it into the test include. Should be merged soon.

**Comment by evoskuil** [comment]
This is now in https://github.com/libbitcoin/libbitcoin-system/pull/1230
