### ISSUE TITLE
Difficulties installing libbitcoin

### ISSUE THREAD

**Issue by MountainMan87119** [libbitcoin/libbitcoin-system#1160]
Any additional info I can dig out will be gladly provided, sure would like to use these libs!

[The_Fight_to_Install_Libbitcoin_Feb_2020.txt](https://github.com/libbitcoin/libbitcoin-system/files/4167991/The_Fight_to_Install_Libbitcoin_Feb_2020.txt)

**Comment by MountainMan87119** [comment]
Whelp, got it compiled on a CentOS 7, but without the ICU.  Just don't have the chops to finesse a custom libboost-all-dev... the "Package boost-devel.x86_64 0:1.53.0-27.el7" doesn't cut it; the Boost I had already, was at least good enough to allow it to compile and install just with ./install.sh.

So unless I should add more details, consider this closed.

For a full build, guess I'd have to get a Debian/Ubuntu distro ~ but for the nonce, see how it goes with this.

**Comment by thecodefactory** [comment]
@MountainMan87119 Looks like you downloaded a version2 install.sh script instead of version3.  Try using the link in the Readme, as it's the properly supported version.

**Comment by MountainMan87119** [comment]
:)  Yep.  Version 3.6.0 installed with everything selected, first shot.  Thanks for all your work and same to the rest of the crew!

**Comment by thecodefactory** [comment]
Glad you got it going!
