### ISSUE TITLE
error When Installing Libbitcoin from Mastering Bitcoin

### ISSUE THREAD

**Issue by xubu1957** [libbitcoin/libbitcoin-system#1161]
Hi guys,
I am trying to run the Mastering Bitcoin C++ codes in Chpt 4 on Ubuntu and its not working.
I used this command to compile the code:
`g++ -o addr addr.cpp $(pkg-config --cflags --libs libbitcoin)`
but the result of this command:
`Package libbitcoin was not found in the pkg-config search path.
Perhaps you should add the directory containing `libbitcoin.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libbitcoin' found
g++: error: addr.cpp: Aucun fichier ou dossier de ce type
g++: fatal error: no input files
compilation terminated.
`

**Comment by evoskuil** [comment]
How did you install libbitcoin, and from which branch?

**Comment by xubu1957** [comment]
I follow the steps mentioned:
https://github.com/libbitcoin/libbitcoin-explorer

**Comment by xubu1957** [comment]
I am a beginner in OS Lunix et Bitcoin
