### ISSUE TITLE
Test oops

### ISSUE THREAD

**Issue by tieugene** [libbitcoin/libbitcoin-system#1168]
Fedora 32 (x64), boost-1.69.0, 'make check':
```
/bin/ld: test/unicode/libbitcoin_test-unicode.o: in function `boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::call_impl<wchar_t const*, wchar_t const*>(wchar_t const* const&, wchar_t const* const&, mpl_::bool_<false>) const':
/usr/include/boost/test/tools/old/impl.hpp:130: undefined reference to `boost::test_tools::tt_detail::equal_impl(wchar_t const*, wchar_t const*)'
/bin/ld: /usr/include/boost/test/tools/old/impl.hpp:130: undefined reference to `boost::test_tools::tt_detail::equal_impl(wchar_t const*, wchar_t const*)'
/bin/ld: /usr/include/boost/test/tools/old/impl.hpp:130: undefined reference to `boost::test_tools::tt_detail::equal_impl(wchar_t const*, wchar_t const*)'
/bin/ld: /usr/include/boost/test/tools/old/impl.hpp:130: undefined reference to `boost::test_tools::tt_detail::equal_impl(wchar_t const*, wchar_t const*)'
/bin/ld: /usr/include/boost/test/tools/old/impl.hpp:130: undefined reference to `boost::test_tools::tt_detail::equal_impl(wchar_t const*, wchar_t const*)'
/bin/ld: test/unicode/libbitcoin_test-unicode.o:/usr/include/boost/test/tools/old/impl.hpp:130: more undefined references to `boost::test_tools::tt_detail::equal_impl(wchar_t const*, wchar_t const*)' follow
collect2: error: ld returned 1 exit status
```

**Comment by evoskuil** [comment]
Is boost test installed?

**Comment by tieugene** [comment]
Boost-test installing automatically with boost-level.
This is the only test that not pass.
(ot 1st, don't know - 'make check' stopped after this point).

**Comment by evoskuil** [comment]
It halted. If equality is missing then there’s a problem with your boost installation.

**Comment by tieugene** [comment]
> there’s a problem with your boost installation.
Maybe: https://koji.fedoraproject.org/koji/taskinfo?taskID=49370565
But check fails anyway (in another distro): https://koji.fedoraproject.org/koji/taskinfo?taskID=49370567

**Comment by evoskuil** [comment]
The Libbitcoin installer can download, build and install all dependencies, including boost. It doesn’t require sudo. From that you can see that when properly installed there is no problem. Boost installation inconsistency is the most common built issue we see.

**Comment by tieugene** [comment]
rpm/deb-based distros (like Fedora/CentOS/Debian/Ubunto/*SuSE etc) are not source-based and does not welcome overwriting system libraries (like boost).
So, I will see inside Fedora 32 (F32) boost problems.
But F33 build is not ok too.

**Comment by evoskuil** [comment]
There is no need to overwrite system libraries. All build dependencies can be installed locally (see no sudo).

**Comment by tieugene** [comment]
I'm trying to make libbitcoin packages into official Fedora/CentOS repo (as official maintainer).
There are many limits for this:
- no network connection during packaging (this is really technical constraint)
- no bandled 3rd-parties inside sources as they are in distro
- desirable - compiling on _all_ (or most of) currently supported OS' (now they are F31..F34^ CentOD7/8).
and many, many other.

So as for my own host - no problems.
But problems are to make normal acceptable packages.

**Comment by evoskuil** [comment]
Ok, but the problems your are encountering are caused by your environment, not by libbitcoin.

**Comment by tieugene** [comment]
> Ok, but the problems your are encountering are caused by your environment, not by libbitcoin.

So, help me to find what is the problem in F33 ("FAILED: 1").
I can't found why

**Comment by evoskuil** [comment]
Sorry, I have no idea what that means or what is even producing it.

**Comment by thecodefactory** [comment]
@tieugene If you want to make official packages, it may be worth making an issue specifically for that.  This one is likely hitting a number of issues.  For example, you could build the entire stack statically, which doesn't require a boost replacement on package install, but does require specific build steps.  What is the command you're running and what is the error you're seeing?  Also, what is it that you need to produce the rpm packages?

**Comment by evoskuil** [comment]
Closed for inactivity.
