### ISSUE TITLE
Android build error 'undefined reference to 'secp256k1_ecdsa_signature_parse_compact'

### ISSUE THREAD

**Issue by alexandrkirilov** [libbitcoin/libbitcoin-system#1173]
Hello all!

I don't know where to ask about it. I am trying to build libbitcoin system for Android and got this issue when run application:
`undefined reference to 'secp256k1_ecdsa_signature_parse_compact'` Full error in log looks like:

`src/math/external/lax_der_parsing.c:20: error: undefined reference to 'secp256k1_ecdsa_signature_parse_compact'
src/math/external/lax_der_parsing.c:142: error: undefined reference to 'secp256k1_ecdsa_signature_parse_compact'
src/math/external/lax_der_parsing.c:146: error: undefined reference to 'secp256k1_ecdsa_signature_parse_compact'
/Users/alexandr/Projects/libbitcoin/prebuilt/libbitcoin/android/armv7/lib/libbitcoin.a(libbitcoin_la-elliptic_curve.o):elliptic_curve.cpp:function libbitcoin::verify_signature(secp256k1_context_struct const*, secp256k1_pubkey, std::__ndk1::array<unsigned char, 32u> const&, std::__ndk1::array<unsigned char, 64u> const&): error: undefined reference to 'secp256k1_ecdsa_signature_normalize'
/Users/alexandr/Projects/libbitcoin/prebuilt/libbitcoin/android/armv7/lib/libbitcoin.a(libbitcoin_la-elliptic_curve.o):elliptic_curve.cpp:function libbitcoin::verify_signature(secp256k1_context_struct const*, secp256k1_pubkey, std::__ndk1::array<unsigned char, 32u> const&, std::__ndk1::array<unsigned char, 64u> const&): error: undefined reference to 'secp256k1_ecdsa_verify'
/Users/alexandr/Projects/libbitcoin/prebuilt/libbitcoin/android/armv7/lib/libbitcoin.a(libbitcoin_la-elliptic_curve.o):elliptic_curve.cpp:function libbitcoin::ec_add(std::__ndk1::array<unsigned char, 32u>&, std::__ndk1::array<unsigned char, 32u> const&): error: undefined reference to 'secp256k1_ec_privkey_tweak_add'`

Is it bug? Or am I missing something?

libbitcoin-system built with parameters:
`./configure --prefix="$PREFIX" --host="${TARGET}" --enable-static --disable-shared --with-boost=${BOOST_DIR} --with-icu=${ICU_DIR} --with-tests=no --with-examples=no;`

secp256k1 built with parameters:
`./configure --host=${TARGET} --prefix=${PREFIX} --disable-shared --enable-static --enable-module-recovery --disable-assembly;`

For iOS/MacOS - all is working perfectly.
When I am building libbitcoin - no any error, writing all is OK, but when I run it in application got this error.

**Comment by alexandrkirilov** [comment]
Is there any information of dependencies version that should be using with libbitcoin?

**Comment by ldz1** [comment]
> Is there any information about dependencies version that should be using with libbitcoin? Boost, secp256k1, ICU?

Default dependencies:
ICU: https://github.com/libbitcoin/libbitcoin-system/blob/bef130bdc8c57808dceab99d6867f3c58acf4e92/install.sh#L62
Boost: https://github.com/libbitcoin/libbitcoin-system/blob/bef130bdc8c57808dceab99d6867f3c58acf4e92/install.sh#L82
secp256k1: https://github.com/libbitcoin/secp256k1

**Comment by evoskuil** [comment]
The automated build works. It relies on the Libbitcoin snapshot of libsecp256k1. This is required as that library is not versioned between breaking changes.

**Comment by evoskuil** [comment]
Information on dependencies is in the [readme](https://github.com/libbitcoin/libbitcoin-system).

**Comment by alexandrkirilov** [comment]
In libbitcoin-system/install.sh defined parameters for secp256k1:

`# Define secp256k1 options.
#------------------------------------------------------------------------------
SECP256K1_OPTIONS=(
"--disable-tests" \
"--enable-module-recovery" \
"--enable-endomorphism")`

If I am following them - I am getting this warning:
`configure: WARNING: unrecognized options: --enable-endomorphism`

That's why I've been asking about version of secp256k1.

**Comment by alexandrkirilov** [comment]
Modern secp256k1 contain only this flags:

--disable-option-checking  ignore unrecognized --enable/--with options
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
  --enable-silent-rules   less verbose build output (undo: "make V=1")
  --disable-silent-rules  verbose build output (undo: "make V=0")
  --enable-shared[=PKGS]  build shared libraries [default=yes]
  --enable-static[=PKGS]  build static libraries [default=yes]
  --enable-fast-install[=PKGS]
                          optimize for fast installation [default=yes]
  --enable-dependency-tracking
                          do not reject slow dependency extractors
  --disable-dependency-tracking
                          speeds up one-time build
  --disable-libtool-lock  avoid locking (might break parallel builds)
  --enable-benchmark      compile benchmark [default=yes]
  --enable-coverage       enable compiler flags to support kcov coverage
                          analysis [default=no]
  --enable-tests          compile tests [default=yes]
  --enable-openssl-tests  enable OpenSSL tests [default=auto]
  --enable-experimental   allow experimental configure options [default=no]
  --enable-exhaustive-tests
                          compile exhaustive tests [default=yes]
  --enable-ecmult-static-precomputation
                          enable precomputed ecmult table for signing
                          [default=auto]
  --enable-module-ecdh    enable ECDH shared secret computation
  --enable-module-recovery
                          enable ECDSA pubkey recovery module [default=no]
  --enable-module-extrakeys
                          enable extrakeys module (experimental)
  --enable-module-schnorrsig
                          enable schnorrsig module (experimental)
  --enable-external-default-callbacks
                          enable external default callback functions
                          [default=no]

**Comment by alexandrkirilov** [comment]
In libbitcoin-system/install.sh mentioned this about downloading secp256k1 from Github

`build_from_github libbitcoin secp256k1 version6 "$PARALLEL" "${SECP256K1_OPTIONS[@]}" "$@"`

But in repository only one branch - master.

**Comment by ldz1** [comment]
> But in repository only one branch - master.

What do you mean? 

https://github.com/libbitcoin/secp256k1/tree/version6

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/secp256k1/tree/version6

**Comment by alexandrkirilov** [comment]
I mean this https://github.com/bitcoin-core/secp256k1 your link is on another repository

**Comment by evoskuil** [comment]
You are in the wrong repository. Libbitcoin has a clone of it because the origin makes breaking changes with no version control.

**Comment by alexandrkirilov** [comment]
What is better to use? I mean what version of libbitcoin better to use? From released version from here https://github.com/libbitcoin/libbitcoin-system/releases or directly from repository? I found a lot of differences between this two versions.

**Comment by evoskuil** [comment]
You should use the version referenced from install.sh in the project you are trying to build. There are no changes in the Libbitcoin versions, they are just cloned so that they can be versioned through branches.

**Comment by alexandrkirilov** [comment]
My apology for this question - Which version of C++ should be using for it? C++11? C++17? I mean compiler definitions. The boost 1.62.0 mentioned in your repository doesn't building with C++17 because of:
`error: no template named 'auto_ptr' in namespace 'std'`
And there are a lot of this kind of errors. 
This point is very critical in case of iOS/Android and Qt.

**Comment by thecodefactory** [comment]
> My apology for this question - Which version of C++ should be using for it? C++11? C++17?

C++11

**Comment by alexandrkirilov** [comment]
I've just build on C++17 for MacOS with this libraries:
-- Secp256k1: from https://github.com/libbitcoin/secp256k1/tree/version6
-- Boost 1.68.0: http://sourceforge.net/projects/boost/files
-- ICU 55.2: https://github.com/unicode-org/icu/archive
-- Libbitcoin: https://github.com/libbitcoin/libbitcoin-system.git

Minimal example is working with Qt 5.15.2 and Qt 6.0 for MacOS.
Next move is to rebuild it with C++17  for iOS/Android.
Thanks everyone for assistance. It's really very tricky to build it for iOS/Android.

**Comment by thecodefactory** [comment]
> Thanks everyone for assistance. It's really very tricky to build it for iOS/Android.

Please help make it better!

**Comment by alexandrkirilov** [comment]
Got it working on iOS https://youtu.be/qAK72ti2PIc Code sample is here https://github.com/ArboreusSystems/arboreus_examples/tree/master/qt/Blockchain/SatoshiWord_v1

Next move to build it for Android.

**Comment by alexandrkirilov** [comment]
If anyone interested - just updated libbitcoin for MacOS with:
-- C++17
-- ICU 67.1
-- Boost 1.72.0
-- Secp256k1 from current repo

All is working. At least on Qt 5.1.5.2 on MacOS all examples is working https://github.com/ArboreusSystems/arboreus_examples/tree/master/qt/Blockchain 

For now rewriting build scripts for iOS with the same parameters. Android build scripts development paused, but not stopped.

**Comment by evoskuil** [comment]
It's not advisable to link libsecp256k1 from the origin repo as they make unversioned breaking changes.

**Comment by evoskuil** [comment]
This is great to see. I'm in the process of updating all dependencies (secp256k1 is done, boost 1.72 almost), also ICU, compilers and Visual Studio solutions (to vs2019). We'll probably stick with vc++11 as the minimum for now, but should be a trivial bump to add c++17 to CI. Also will be verifying everything locally and in CI on iOS and Ubuntu.

**Comment by evoskuil** [comment]
I'm very interested in getting QT integration working cleanly on all platforms, and supporting ARM builds. Please ping me if you are still at it!

**Comment by evoskuil** [comment]
Closing this as complete, added a new issue for tracking Android, etc. https://github.com/libbitcoin/libbitcoin-system/issues/1193

**Comment by alexandrkirilov** [comment]
I am still on it. Sent a ping via e-mail. Check your mail box.
