### ISSUE TITLE
Conan Support

### ISSUE THREAD

**Issue by npodonnell** [libbitcoin/libbitcoin-system#1175]
Hello
Is there a plan to make libbitcoin available on [conan center](https://conan.io/center/)?

**Comment by thecodefactory** [comment]
There was some talk of conan in the slack channel a while back, but I don't believe there are specific plans at the moment.  Interested in helping out there?

**Comment by npodonnell** [comment]
Yes, I'd love to help out. 

I'm setting up a project at the moment which consumes libbitcoin, I'm using conan for dependency management, but ideally I'd like to have all dependencies managed by conan.

**Comment by evoskuil** [comment]
The beauty of open source is that you can do it and submit a pull request. It would have to be added to libbitcoin-build as generated code, which maintainers can help with.

**Comment by evoskuil** [comment]
Closed for lack of activity.
