### ISSUE TITLE
Libbitcoin-system examples. Where to find?

### ISSUE THREAD

**Issue by alexandrkirilov** [libbitcoin/libbitcoin-system#1176]
Hello all!
I've tried to find examples for current version of libbitcoin-system. All that I found is outdated https://libbitcoin.dyne.org/doc/ Is there any valid examples?

PS. I've seen the directory examples that is in repository. There are only one example - Satoshi Word.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-system/wiki

**Comment by alexandrkirilov** [comment]
Thx a lot
