### ISSUE TITLE
Need a tutorial for install libbitcoin on windows

### ISSUE THREAD

**Issue by cheaterNo1** [libbitcoin/libbitcoin-system#1178]
Dear libbitcoin admins!
I'd looked for a simple way to install libbitcoin on vs c++ 19 (windows) but I found no tutorial for that.

**Comment by evoskuil** [comment]
This support hasn’t yet been tested and included. You are welcome to extend the existing pattern and try it out. I doubt there would be any material issues.

**Comment by cheaterNo1** [comment]
> This support hasn’t yet been tested and included. You are welcome to extend the existing pattern and try it out. I doubt there would be any material issues.

Thanks for your immediate reply, I will try it myself.
