### ISSUE TITLE
[wiki] Fix broken 'merchants' link in Glossary

### ISSUE THREAD

**Issue by yojoots** [libbitcoin/libbitcoin-system#1179]
There's a typo on one of the 'merchants' link in the Glossary.md page of the libbitcoin-system wiki, breaking the link.

Easy fix: https://github.com/yojoots/libbitcoin-system-wiki/commit/fdcb51585e8677bb564a69073b1449c6ef30356d

**Comment by evoskuil** [comment]
Fixed
