### ISSUE TITLE
qrcode__invoke__qrencode_data__success fail with updated dependencies.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-system#1196]
https://travis-ci.org/github/libbitcoin/libbitcoin-system/jobs/761791762#L9000

```
make[2]: *** [test-suite.log] Error 1
make[1]: *** [check-TESTS] Error 2
make: *** [check-am] Error 2
Running 2375 test cases...
Platform: Mac OS
Compiler: Clang version 9.1.0 (clang-902.0.39.2)
STL     : libc++ version 5000
Boost   : 1.72.0
test/wallet/qrcode.cpp:113: fatal error: in "qrcode_tests/qrcode__invoke__qrencode_data__success": critical check std::memcmp(encoded_qrcode.data(), expected_data, expected_data_length) == 0 has failed
```

All builds with these dependencies have same failure.

**Comment by evoskuil** [comment]
It's not unexpected that this test might fail given a dependency change. The binary encoding of an image may differ without affecting its validity as a qrcode.

**Comment by evoskuil** [comment]
After modifying the test to compare based16 encoded data, the following is available:

```
030000001d000000c1c1c1c1c1c1c1c084000100010101000101010001c0c1c1c1c1c1c1c1c1c0c0c0c0c0c1c085000100000000010001010001c0c1c0c0c0c0c0c1c1c0c1c1c1c0c1c084000000010000000000000001c0c1c0c1c1c1c0c1c1c0c1c1c1c0c1c085010100010100010101000001c0c1c0c1c1c1c0c1c1c0c1c1c1c0c1c084010000000001010100000101c0c1c0c1c1c1c0c1c1c0c0c0c0c0c1c085010001010100010000010000c0c1c0c0c0c0c0c1c1c1c1c1c1c1c1c091909190919091909190919091c0c1c1c1c1c1c1c1c0c0c0c0c0c0c0c084010101000000000000010000c0c0c0c0c0c0c0c08585858585849185850100010001010101000001018584858485848584020203020303900303000100010101000001010101000100010000010103020302030391020200010000000001000000000000000101010100000202020302029002030000000100010000000100000100010001000100020203030203910203010100010101010001000101000000010001000002030303030290020303000000010101010000010101010101010100010203030303029103020203010101000101010100010001000101010000020203020302900303030301000000000100010001000101010100000002020303030391020302020100010101010000000000000100000101010302020302029002020202000100010101000101010101000100010101030203020202910202020300000001010100000000010000010100000003020302030390020303020001000101000001000001010100010001010302030303029102020302000101010001010000a1a1a1a1a100010100c0c0c0c0c0c0c0c0810303000000010101010101a1a0a0a0a101010101c1c1c1c1c1c1c1c0850203010101000101000101a1a0a1a0a100010000c1c0c0c0c0c0c1c0840202010000010101000001a1a0a0a0a100000101c1c0c1c1c1c0c1c0850202010000000100010000a1a1a1a1a101010101c1c0c1c1c1c0c1c0850302000101000101010100010000000100010101c1c0c1c1c1c0c1c0850203000001010101000000000001010100010100c1c0c0c0c0c0c1c0850202000101000101000000010000010100000100c1c1c1c1c1c1c1c0850203000100010000000001000100000101010000
 != 
030000001d000000c1c1c1c1c1c1c1c084020302030303020303030203c0c1c1c1c1c1c1c1c1c0c0c0c0c0c1c085020302020202030203030203c0c1c0c0c0c0c0c1c1c0c1c1c1c0c1c084020202030202020202020203c0c1c0c1c1c1c0c1c1c0c1c1c1c0c1c085030302030302030303020203c0c1c0c1c1c1c0c1c1c0c1c1c1c0c1c084030202020203030302020303c0c1c0c1c1c1c0c1c1c0c0c0c0c0c1c085030203030302030202030202c0c1c0c0c0c0c0c1c1c1c1c1c1c1c1c091909190919091909190919091c0c1c1c1c1c1c1c1c0c0c0c0c0c0c0c084030303020202020202030202c0c0c0c0c0c0c0c08585858585849185850302030203030303020203038584858485848584020203020303900303020302030303020203030303020302030202030303020302030391020202030202020203020202020202020303030302020202020302029002030202020302030202020302020302030203020302020203030203910203030302030303030203020303020202030203020202030303030290020303020202030303030202030303030303030302030203030303029103020203030303020303030302030203020303030202020203020302900303030303020202020302030203020303030302020202020303030391020302020302030303030202020202020302020303030302020302029002020202020302030303020303030303020302030303030203020202910202020302020203030302020202030202030302020203020302030390020303020203020303020203020203030302030203030302030303029102020302020303030203030202a1a1a1a1a102030302c0c0c0c0c0c0c0c0810303020202030303030303a1a0a0a0a103030303c1c1c1c1c1c1c1c0850203030303020303020303a1a0a1a0a102030202c1c0c0c0c0c0c1c0840202030202030303020203a1a0a0a0a102020303c1c0c1c1c1c0c1c0850202030202020302030202a1a1a1a1a103030303c1c0c1c1c1c0c1c0850302020303020303030302030202020302030303c1c0c1c1c1c0c1c0850203020203030303020202020203030302030302c1c0c0c0c0c0c1c0850202020303020303020202030202030302020302c1c1c1c1c1c1c1c0850203020302030202020203020302020303030202
```

Can convert these to binary and view as PNG to determine if they are functionally equivalent.

**Comment by thecodefactory** [comment]
After base16-decode and sending through qrencode and outputting as png files, both of those data streams appear identical to me.

**Comment by thecodefactory** [comment]
![a1](https://user-images.githubusercontent.com/5875399/110516674-e5ffc280-80d7-11eb-9d27-2ce8c50cf5b4.png)
![b1](https://user-images.githubusercontent.com/5875399/110516683-e9934980-80d7-11eb-8ada-48050e749863.png)

Generated images in order.

**Comment by evoskuil** [comment]
These are qrencode output. Should only go through base16 and png to verify. If qrencoded again they should differ significantly. Please confirm.

**Comment by evoskuil** [comment]
Also should scan to fully verify result.

**Comment by thecodefactory** [comment]
There are no cli tools to do that, and I didn't write code to do the specific conversion.  I decoded that data and sent to qrencode, which can output in png, which was done.  Agreed, it's different content.  But note that the base16 data appears identical except for the whitespace gaps `010000000001010100000101` --> `030202020203030302020303`, so I suspect it's a library default that changed across versions.

**Comment by evoskuil** [comment]
Even if it’s a trivially different number, at encoding it should result is a different qrcode. So something seems off.

**Comment by thecodefactory** [comment]
Give it a shot using the cli tools from our stack.  It's just bx base16-decode [data] | qrencode -o data.png

**Comment by evoskuil** [comment]
As I said, that’s not a valid test.

**Comment by thecodefactory** [comment]
Ok. I had agreed to that already. I was commenting that it's not a visually different qr code (at least to me)

**Comment by evoskuil** [comment]
Qrencoding converts a number to a bitmap. Different number different bitmap. It’s not an image conversion.

**Comment by evoskuil** [comment]
I’m more interested in why doing that rencoding didn’t create a different result.

**Comment by thecodefactory** [comment]
I'm arguing it's because they are effectively the same bitmap ...

**Comment by evoskuil** [comment]
You are missing my point, read it more closely.

**Comment by evoskuil** [comment]
qrcode(1) should not look anything like qrcode(2).

**Comment by thecodefactory** [comment]
Yet they do ...

**Comment by evoskuil** [comment]
Which seems like a more significant (actual) bug.

**Comment by thecodefactory** [comment]
Yeah.  I don't have a qrcode scanner to verify at the moment

**Comment by evoskuil** [comment]
Can a qrcode even support such a massively long number?

**Comment by thecodefactory** [comment]
Don't see why not.  The data is 849 bytes.  If you pass too much data, you see this at the cli:

```
$ qrencode -r test -o test.qr.png
Input data is too large.
```

**Comment by evoskuil** [comment]
Just that it has to be bounded in order to fit on a bounded set of image pixels.

**Comment by evoskuil** [comment]
It requires at least 2^(8*849) different representations to be able to represent the domain of an 849 byte number, not counting error correction and alignment pixels.

**Comment by evoskuil** [comment]
But I suppose that means 8*849=6792 pixels, given two states each.

**Comment by evoskuil** [comment]
![E550F7A7-C175-4801-9DBE-164C8D3E94A9](https://user-images.githubusercontent.com/1369335/110535036-9ec40280-80d4-11eb-929f-47b4f19d0c96.jpeg)

iPhone pixels

**Comment by evoskuil** [comment]
849 bytes, 8 bits each, two states per bit.

**Comment by thecodefactory** [comment]
> That’s a square of 3396 x 3396

**Comment by evoskuil** [comment]
Oh, duh, need sqrt

**Comment by evoskuil** [comment]
So need 83^2, which should fit :).

**Comment by evoskuil** [comment]
But doesn’t explain why the two images are the same. I’m hoping they scan differently, returning the original 849 byte values.

**Comment by thecodefactory** [comment]
Same.  That would verify that my eyes are not good qrcode scanners :-)

**Comment by evoskuil** [comment]
But still left with test reliability.

**Comment by evoskuil** [comment]
It’s in the compression.

**Comment by thecodefactory** [comment]
Or that there are thresholds in qr encoding that are different but considered the same.   Not sure. It's possible the test was flawed from the start.

**Comment by evoskuil** [comment]
If the code was good the test was flawed :))

**Comment by evoskuil** [comment]
But that’s why we have them.

**Comment by evoskuil** [comment]
Decoders are designed to return text, so it’s very hard to compare using scanning tools. But visually it’s pretty easy to see those are identical images. Pasting one on top of the other shows no differences.

I think the answer is to add a qrdecode function (and eventually command) so that both qrencode and png conversions can be round-tripped.

**Comment by evoskuil** [comment]
I think also that it would be nice if we could add an intermediate command that outputs to bitmap,,using our own source to translate from qrencode output to bitmap. This should be a simple mapping requiring no compression (zlib + libpng). That would allow us to drop two dependencies. Or we could retain the dependencies and pipe bitmaps into png, though that’s a generic function which probably isn’t worth maintaining in the libraries.

**Comment by evoskuil** [comment]
Seems pretty straightforward, just create a `to_chunk({...})` with the necessary set of parameters.

https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFF6.pdf

**Comment by evoskuil** [comment]
Dropping two dependencies and outputting `tiff` would make me very happy. I may write this as it will take me less time than updating the dependencies.

**Comment by evoskuil** [comment]
qrencode is actually a very clean and well maintained dependency. zlib and libpng aren’t so much.

**Comment by evoskuil** [comment]
This would also make adding vc++ support much easier. I’m looking at switching from NuGet to vcpkg, as it’s much better for native code. The only issue is that I’ll need to still package secp256k1. But both libzmq and boost are current packages being maintained there, as is qrencode (and libpng and zlib). But dropping from 5 to 3 dependencies is a godsend.

**Comment by evoskuil** [comment]
I don’t believe libqrencode supports decoding. But there is a qrdecode library here.

https://github.com/josephholsten/libdecodeqr/tree/master/libdecodeqr

Both are GPL licenses. We can probably just incorporate the sources for both and eliminate a third dependency while supporting round trip. Decoding appears to support jpg, png and bmp.

**Comment by evoskuil** [comment]
This failure also affect BX tests.

https://travis-ci.org/github/libbitcoin/libbitcoin-explorer/jobs/762088243#L10513

**Comment by evoskuil** [comment]
Given that qrencode has no dependencies, it must be the case that it alone has changed the output. As long as we can rely on a specific version the test is sufficient. Given [incorporation of qrencode into libbitcoin-system](https://github.com/libbitcoin/libbitcoin-system/issues/1198) this will no longer be an issue. Until then it is sufficient to simply update the test with the new output. This will break against a future version of qrencode with formatting changes, but that's fine.

Also, I believe the images may be matching because their resolution is too low for the data, given the block size of each pixel (21 x 21).

**Comment by evoskuil** [comment]
Disabled test, will replace once qrcode source is incorporated.

**Comment by evoskuil** [comment]
Resolved in master, will update this test in Version3 now that the dependencies are also updated.
