### ISSUE TITLE
use ld in my code

### ISSUE THREAD

**Issue by medeirosfalante** [libbitcoin/libbitcoin-system#1220]
is possible use -l in g++ compiler ?

i try but have a error:
cannot find -llibbitcoin-system

**Comment by evoskuil** [comment]
g++ is commonly used and regularly tested. We’ll need more information about the error to help you.

**Comment by medeirosfalante** [comment]
i use $(pkg-config --cflags libbitcoin-system --libs libbitcoin-system). 
example build with g++
 g++ -std=c++11 -o hd.app main.cpp $(pkg-config --cflags libbitcoin-system --libs libbitcoin-system) -lgmp

**Comment by evoskuil** [comment]
Error message and context?

**Comment by evoskuil** [comment]
Or repro source.

**Comment by evoskuil** [comment]
How did you install Libbitcoin? If you used a prefix fir, as recommended, it won’t be found without using explicit paths as it’s not in your system paths.

**Comment by medeirosfalante** [comment]
work with $(pkg-config --cflags libbitcoin-system --libs libbitcoin-system).
