### ISSUE TITLE
wrong path for vcvarsall.bat in build_all.bat if VS 2017 Enterprise was installed

### ISSUE THREAD

**Issue by Stonica** [libbitcoin/libbitcoin-system#1223]
I found if Visual Studio 2017 Enterprise was installed we must change line 4 of build_all.bat from:

CALL build_base.bat vs2017 libbitcoin-system "Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"

to

CALL build_base.bat vs2017 libbitcoin-system "Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build"

**Comment by evoskuil** [comment]
Version3 branch? Probably so, since the paths were recently updated.

**Comment by evoskuil** [comment]
These are primarily maintainer tools.
