### ISSUE TITLE
Reference dictionaries are not normalized.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-system#1227]
While the reference dictionary from Trezor (BIP39) and that from Electrum use the "same" wordlists, the words are differently normalized. As a result they do not show a difference in git diff tools, however test results vary. Example of own word, from the two references and in our dictionary and our test case:

![text](https://user-images.githubusercontent.com/1369335/113522821-95557b00-9558-11eb-95bb-e19e6b977268.png)

![hex](https://user-images.githubusercontent.com/1369335/113522824-9686a800-9558-11eb-8072-3cad43e9143e.png)

**Comment by evoskuil** [comment]
In the test cases where the dictionary encoding varies from the test vector encoding, `validate_mnemonic(create_mnemonic(entropy, vector.language), vector.language)` succeeds because text is normalized, however intermediate tests cases that do not perform normalization fail.

**Comment by evoskuil** [comment]
Electrum NFKD normalizes the dictionary [on read](https://github.com/spesmilo/electrum/blob/master/electrum/mnemonic.py#L123), BIP39 [assumes](https://github.com/trezor/python-mnemonic/blob/master/mnemonic/mnemonic.py#L93) dictionaries are pre-normalized. Both normalize the mnemonic and passphrase.

**Comment by evoskuil** [comment]
Reading the entire dictionary and normalizing it on each load, or normalizing each of its word on compare is hugely wasteful, so it makes sense for dictionaries to be pre-normalized. But given that seed creation normalizes the mnemonic sentence, it doesn't make sense to not do so before looking up the words upon validation. Otherwise a mnemonic that creates a valid seed is later rejected as an invalid mnemonic.

**Comment by evoskuil** [comment]
This is complete in pending PR https://github.com/libbitcoin/libbitcoin-system/pull/1230

**Comment by junderw** [comment]
> Will also add test loops to ensure they are lexically sorted

FYI, due to error in the BIP39 wordlist vetting process, Japanese is not lexically sorted, so binary search is not possible.

**Comment by evoskuil** [comment]
The current implementation unit tests each dictionary for a lexical sort and this result is flagged in the config of each dictionary. That’s used to branch of the sort methodology.
