### ISSUE TITLE
How to generate 1 million P2SH address with known private keys

### ISSUE THREAD

**Issue by Stonica** [libbitcoin/libbitcoin-system#1228]
Suppose I have 1 million byte[32] array which filled with random bytes and I am to use them as raw bytes of private keys.
Could you help me (a code snippet) how to generate the P2SH address of this 1 million private key using libbitcoin-system, as fast as possible?

**Comment by evoskuil** [comment]
Do you want independent wallets or a single hd wallet?

**Comment by Stonica** [comment]
> independent wallet

independent wallets

**Comment by evoskuil** [comment]
I'm not sure I understand "the P2SH address of this 1 million private key[s]", do you want to make a single multisig address with 1 million public keys?

**Comment by Stonica** [comment]
> 
> 
> I'm not sure I understand "the P2SH address of this 1 million private key[s]", do you want to make a single multisig address with 1 million public keys?

In simple words, I need `Your_Recommended_Function` code in below snippet:

```
//private_key1 is a byte array that contain raw bytes of my private key
unsigned char private_key1[32]={0xb4,0xaf,0x98,0x1a,0xb4,0xaf,0x98,0x1a,0xb4,0xaf,0x98,0x1a,0xb4,0xaf,0x98,0x1a,0xb4,0xaf,0x98,0x1a,0xb4,0xaf,0x98,0x1a,0xb4,0xaf,0x98,0x1a,0xb4,0xaf,0x98,0x1a};

//Here we are to generate 22 byte length Segwit pay to script address corresponding to private_key1
unsigned char[22] Segwit_P2SH_Address=Your_Recommended_Function(private_key1);
```

**Comment by evoskuil** [comment]
I don’t believe there is a Libbitcoin witness template yet. All you need to do is construct the script object using op codes and data, generate the address hash and serialize. Base32 encoding is implemented so there should be everything you need. Other script template examples are in the chain::script class.

**Comment by evoskuil** [comment]
I stand corrected. There are witness address templates and a wrapper class in libbitcoin.

```cpp
    using namespace bc::system;
    using namespace bc::system::wallet;

    constexpr auto p2wsh = witness_address::address_format::witness_script_hash;

    const ec_secret secret
    {
        0xb4, 0xaf, 0x98, 0x1a, 0xb4, 0xaf, 0x98, 0x1a,
        0xb4, 0xaf, 0x98, 0x1a, 0xb4, 0xaf, 0x98, 0x1a,
        0xb4, 0xaf, 0x98, 0x1a, 0xb4, 0xaf, 0x98, 0x1a,
        0xb4, 0xaf, 0x98, 0x1a, 0xb4, 0xaf, 0x98, 0x1a
    };

    const ec_private private_key{ secret };
    const witness_address witness{ private_key, p2wsh };

    if (witness)
    {
        // encoded bech32 address
        const auto bech32 = witness.encoded();

        // output script object
        const auto script = witness.output_script();

        base32 out;
        if (decode_base32(out, bech32))
        {
            // decoded bech32 address
            const auto prefix = out.prefix;
            const auto payload = out.payload;
        }
    }
```

**Comment by evoskuil** [comment]
Is this sufficient/resolved?

**Comment by Stonica** [comment]
yes, thanks
