### ISSUE TITLE
Building on Windows (Visual Studio 2019) first timer

### ISSUE THREAD

**Issue by forexstudies** [libbitcoin/libbitcoin-system#1231]
So I like to use this library to create a wallet to generate addresses for various coins on Windows using VS 2019. 
In the absence of a step by step how to document I couldn't even build the libbitcoin-system on VS2019. anyone to help me set this up in VS2019..
The cmake error log says:

_Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/CPPSources/libbitcoin/system/builds/cmake/out/build/x64-Debug/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MVisualStudio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_d6a5c && [1/2] Building C object CMakeFiles\cmTC_d6a5c.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_d6a5c.dir/CheckIncludeFile.c.obj 

C:\PROGRA~2\MVISUA~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_d6a5c.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_d6a5c.dir\ /FS -c CheckIncludeFile.c

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed._

**Comment by evoskuil** [comment]
The CMake builds do not support VS. There is a full set of solution and project files with instructions. I build with VS several times a day.

**Comment by forexstudies** [comment]
Not having much luck, I already have Boost build and installed and is available in my VS environment.
When I try to use build_all.bat as in the instructions i get the following:

C:\CPPSources\libbitcoin\system\builds\msvc\build>build_all.bat
Downloading libbitcoin vs2017 dependencies from NuGet
Feeds used:

Restoring NuGet package boost_date_time-vc141.1.72.0.
Restoring NuGet package boost_locale-vc141.1.72.0.
Restoring NuGet package boost_filesystem-vc141.1.72.0.
Restoring NuGet package boost.1.72.0.
Restoring NuGet package boost_iostreams-vc141.1.72.0.
Restoring NuGet package boost_log_setup-vc141.1.72.0.
Restoring NuGet package boost_atomic-vc141.1.72.0.
WARNING: Unable to find version '1.72.0' of package 'boost_atomic-vc141'.
WARNING: Unable to find version '1.72.0' of package 'boost_date_time-vc141'.
WARNING: Unable to find version '1.72.0' of package 'boost_log_setup-vc141'.
WARNING: Unable to find version '1.72.0' of package 'boost_locale-vc141'.
Restoring NuGet package boost_system-vc141.1.72.0.
Restoring NuGet package boost_regex-vc141.1.72.0.
WARNING: Unable to find version '1.72.0' of package 'boost_system-vc141'.
Restoring NuGet package boost_chrono-vc141.1.72.0.
Restoring NuGet package boost_log-vc141.1.72.0.
WARNING: Unable to find version '1.72.0' of package 'boost_filesystem-vc141'.
WARNING: Unable to find version '1.72.0' of package 'boost_regex-vc141'.
WARNING: Unable to find version '1.72.0' of package 'boost_iostreams-vc141'.
Restoring NuGet package boost_program_options-vc141.1.72.0.
WARNING: Unable to find version '1.72.0' of package 'boost_log-vc141'.
Restoring NuGet package boost_thread-vc141.1.72.0.
WARNING: Unable to find version '1.72.0' of package 'boost'.
WARNING: Unable to find version '1.72.0' of package 'boost_chrono-vc141'.
WARNING: Unable to find version '1.72.0' of package 'boost_thread-vc141'.
Restoring NuGet package secp256k1_vc141.0.1.0.19.
WARNING: Unable to find version '1.72.0' of package 'boost_program_options-vc141'.
WARNING: Unable to find version '0.1.0.19' of package 'secp256k1_vc141'.
Unable to find version '1.72.0' of package 'boost_atomic-vc141'.
Unable to find version '1.72.0' of package 'boost_date_time-vc141'.
Unable to find version '1.72.0' of package 'boost_log_setup-vc141'.
Unable to find version '1.72.0' of package 'boost_locale-vc141'.
Unable to find version '1.72.0' of package 'boost_system-vc141'.
Unable to find version '1.72.0' of package 'boost_filesystem-vc141'.
.....

**Comment by evoskuil** [comment]
Just build from the ide after setting up the environment as per the readme.

**Comment by forexstudies** [comment]
unless you are referring to another Readme I am not aware of, it says under Windows section, (in the Readme) I should use build_all.bat where are these elusive instructions to set up my environment? Do i need other tools except my VS 2019 ide?

**Comment by evoskuil** [comment]
“After cloning the the repository the libbitcoin build can be performed from within Visual Studio…” you need the nuget packages as described and VS.

**Comment by evoskuil** [comment]
People sometimes experience problems with the batch files, which are really meant for maintainers to build the full set of configurations. They aren’t hardened for environmental things like long paths. It looks like your nuget config has a problem. As long as the solution can find the nuget dependencies the projects should build from within VS.

**Comment by forexstudies** [comment]
I did clone the repository and the NuGet package manager kicked off but I ran into this error:
"Unable to find version 1.72.0 of package 'boost_date_time-vc141' https://nuget.org: Failed to fetch results from V2 feed at 'https://www.nuget.org/FindPackagesById()?id='boost_date_time-vc141'&semVerLevel=2.0.0' with the following message Response status code does not indicate success: 404 (Not Found)"

**Comment by evoskuil** [comment]
https://www.nuget.org/packages/boost_date_time-vc141/1.72.0

**Comment by forexstudies** [comment]
When I cloned the project first I had to migrate/convert it to  VS 2019 project.
U checked my NuGet packages.config looks ok but I have a warning:

_Warning		The 'packages' element is not declared.	libbitcoin-system	C:\source\repos\libbitcoin-system\builds\msvc\vs2017\libbitcoin-system\packages.config_

Even though I can see the package from the link you send above I am still getting the same error.

**Comment by forexstudies** [comment]
Do you have configs for vs2019?

**Comment by evoskuil** [comment]
There is no need to convert to vs2019, just cancel the conversion prompt.

**Comment by evoskuil** [comment]
The URL is generated by nuget and the packages are served by it. The package ID is correct. So either nuget is broken or your environment isn’t configured for it.

**Comment by evoskuil** [comment]
The error above implies your package config isn’t correct.

**Comment by forexstudies** [comment]
Thank you 
It was my NuGet configuration which was wrong I updated it, the only error I am now getting is:

LNK1104	cannot open file 'libboost_thread-vc142-mt-sgd-x64-1_72.lib'	libbitcoin-system

**Comment by evoskuil** [comment]
Make sure the `boost_thread-vc141.1.72.0.0` package is in the nuget repo.

**Comment by evoskuil** [comment]
Oh, your error says it's looking for vc142. Something in your project got updated to VS2019.

**Comment by evoskuil** [comment]
I build in VS2019, it will be fine as long as you don't let it upgrade the project when it first opens. I'll be adding VS2019 solutions eventually.

**Comment by forexstudies** [comment]
Yeah I tried to clone the project and not upgrade the PlatformToolset to vc142 the problem is I dont have VS 2017 so after downloading the NuGet packages it just failed to build it requires vc141 Platform Toolset

**Comment by evoskuil** [comment]
Probably just need to install VS2017 and then you can build in VS2019, without upgrading. I've got all versions of VS installed so I don't notice it.
