### ISSUE TITLE
Could not build library on Windows in VS2019 

### ISSUE THREAD

**Issue by mechark** [libbitcoin/libbitcoin-system#1232]
In VS2017 library is built, but in VS2019 i have a few issues:

- libbitcoin::system::interprocess::CreateFileW': ambiguous call to overloaded function
- libbitcoin::system::interprocess::CreateFileW': ambiguous call to overloaded function (compiling source file..\..\..\..\src\utility\flush_lock.cpp)
- libbitcoin::system::interprocess::CreateFileW': ambiguous call to overloaded function (compiling source file ..\..\..\..\src\utility\interprocess_lock.cpp)
- typedef "interprocess_security_attributes" may not be used in an elaborated type specifier

**Comment by evoskuil** [comment]
VS2019 solutions are not provided as the new compiler is not yet supported. You can build in VS2019 but should not allow VS to upgrade the projects.

**Comment by mechark** [comment]
Yeah, I have read about that already. Now I can build the library, but can not use it because of strange errors in library source code. When I click on the one of the errors in errors list and go ro file with "error", I don't see any errors at all.
30 июл. 2021 г., 2:46 +0300, Eric Voskuil ***@***.***>, написал (-а):

**Comment by evoskuil** [comment]
Sorry, need a better description than what happens when you click. I build the same in VS2019 with no errors.

**Comment by mechark** [comment]
I include libbticoin lib to my own dll library. So here some screenshots of the project properties and errors that occure when i try to build it and changing project configuration doesn't help me.
![2021-07-30](https://user-images.githubusercontent.com/61243026/127684537-37e15463-e211-499f-a4f0-973100b592e1.png)
![2021-07-30 (1)](https://user-images.githubusercontent.com/61243026/127684563-7127a8bf-f207-4d07-8889-c6730d55478a.png)
![2021-07-30 (2)](https://user-images.githubusercontent.com/61243026/127684602-f053169c-e412-48ac-9fe9-a55e4ee2e1c2.png)
![2021-07-30 (3)](https://user-images.githubusercontent.com/61243026/127684621-7424a1b8-a4fc-489c-afc6-4fd9d2c98258.png)
![2021-07-30 (4)](https://user-images.githubusercontent.com/61243026/127684647-93d9a98a-37c0-478a-8d8d-dcc73bbda9ce.png)

**Comment by evoskuil** [comment]
> The libbitcoin dynamic (DLL) build configurations do not compile, as the exports have not yet been fully implemented. These are currently disabled in the build scripts but you will encounter numerous errors if you build then manually.

https://github.com/libbitcoin/libbitcoin-system#readme

**Comment by mechark** [comment]
![2021-07-30 (6)](https://user-images.githubusercontent.com/61243026/127688695-ebca6b67-d84a-4a78-89e2-4ff0520e0cce.png)

**Comment by evoskuil** [comment]
This appears to be an error in your project, not the library build. Do the libbitcoin tests all build and pass?

**Comment by evoskuil** [comment]
Also note that there is a DLL interface error in the build.

**Comment by mechark** [comment]
![2021-07-30 (7)](https://user-images.githubusercontent.com/61243026/127699072-96bf1f4d-1d5c-4073-babc-5546dde4b4e6.png)

**Comment by evoskuil** [comment]
This doesn’t show test execution.

**Comment by evoskuil** [comment]
The nine other Libbitcoin libraries successfully build and line against system, and several of them (node, server, explorer) build statically-linked executables. These work in VS2019 as long as the compiler is not upgraded for any of the VS2017 
solutions.

**Comment by mechark** [comment]
I built a new project in VS2017 and i see the same errors.
https://github.com/libbitcoin/libbitcoin-system/issues/1232#issuecomment-890036935

**Comment by mechark** [comment]
Yes, I fully understand it. I know that this is not your responsibility, but what can I do to fix those erros? I don't understand why are they appearing.

**Comment by evoskuil** [comment]
It appears that your linkage is inconsistent. That can be a challenge in vc++. I recommend modifying the examples project source files and building up from there.

**Comment by mechark** [comment]
I need to use a few libs(system, blockchain, consensus) therefore i should make a separate project.

**Comment by evoskuil** [comment]
The example project is a separate project.

**Comment by mechark** [comment]
https://stackoverflow.com/questions/9078513/how-do-you-properly-link-to-a-static-library-using-g
This helped me fix errors. I know it's incorrect to edit library source code, but now it's working poperly and i can include it to my own library without any erros.

**Comment by evoskuil** [comment]
You have fixed an error that does not exist, as the libraries already link properly to statically-compiled executable binaries, including bx, bn, and bs.exe. DLL export statements are not a correct solution to a static linkage issue.

**Comment by mechark** [comment]
> Also note that there is a DLL interface error in the build.

Hi. Can you explain what it means, please.

**Comment by evoskuil** [comment]
It means that DLL builds are not supported. The libraries must be statically-linked, as mentioned above and in the readme.

**Comment by evoskuil** [comment]
Closing issue as not supported (vs2019 and DLL linkage).

**Comment by mechark** [comment]
> It means that DLL builds are not supported. The libraries must be statically-linked, as mentioned above and in the readme.

I'v noticed libbitcoin-system solution has a StaticDebug mode by default and when solution set to it libbitcoin-system-examples works fine, but if i change it to Debug examples project won't be able to work properly even if i set the runtime to MTd. I think this is the main reason of my problem.

**Comment by evoskuil** [comment]
That is how the builds are named. The individual projects have DLL builds, but DLL linkage is not supported. There are a significant number if issues with supporting DLL exports.

**Comment by mechark** [comment]
So why is it doesn't compile in Debug and compile successfully in StaticDebug. What am I missing?

**Comment by evoskuil** [comment]
If it’s not static then it’s dynamic (DLL).

**Comment by mechark** [comment]
It's very strange. I make a project template from the libbitcoin-system-examples project and it doesn't works properly too. I don't know what i'll do far away, but thank you for your replying to me, sorry for troubling you.

**Comment by evoskuil** [comment]
Does the non-upgraded examples project compile statically for you? I build it every Fay with no problems in vs2019.

**Comment by mechark** [comment]
Yes, examples project compile statically,because if it doesn't I'll be see an errors while running it, but even the exact copy of this project with the same project properties setup does not compiles. It produces a compiler error which I mentioned above, so is it means that I linking dynamically for some obscurely reasons?

**Comment by evoskuil** [comment]
Clearly it’s not exactly the same. I recommend editing the examples project and working from that.
