### ISSUE TITLE
why is there a code for ring signatures?

### ISSUE THREAD

**Issue by ddolgov** [libbitcoin/libbitcoin-system#1233]
I've started looking at the libbitcoin code and noticed there is a ring signatures implementation. Why is it there and where is it used, if you don't mind me asking? I could not find any discussion in pull requests/issues...

**Comment by thecodefactory** [comment]
https://github.com/libbitcoin/libbitcoin-system/pull/947

**Comment by ddolgov** [comment]
Thanks! Yeah, I saw that thread, but there is no information on why is it needed and where ist it used, as far as I can tell

**Comment by evoskuil** [comment]
It is not used in any Libbitcoin feature. It a library, so tests are sufficient.
