### ISSUE TITLE
Compilation error with boost 1.77.0

### ISSUE THREAD

**Issue by scpeters** [libbitcoin/libbitcoin-system#1234]
The `boost/interprocess/detail/posix_time_types_wrk.hpp` header used in [include/bitcoin/system/unicode/file_lock.hpp](https://github.com/libbitcoin/libbitcoin-system/blob/72611794b3d177b060bf0fc733f1ec71bc4d8f57/include/bitcoin/system/unicode/file_lock.hpp#L22) has been removed from boost as of version 1.77.0 (see https://github.com/boostorg/interprocess/commit/0fcdbc4083aac62e5e2f801a64e00afd5ee6e681) which causes a compilation error. First noticed in https://github.com/Homebrew/homebrew-core/pull/83243

**Comment by evoskuil** [comment]
This code has been removed in a pending master pull request. If you require a resolution for version3 I suggest a issuing pull request.

**Comment by iMichka** [comment]
Hi. Homebrew maintainer here.

We are in the process to update boost from 1.76.0 to 1.78.0 in Homebrew. Can you give some more details about what pull request was pending so we can have a look. Not sure we have much bandwidth on our side to move things forward though.

Could you also confirm that you only support boost 1.76.0 for the time being, and if there are plans to add support for newer versions?

**Comment by evoskuil** [comment]
We have no plans to update v3, and there is no PR associated with this issue. This will eventually be resolved in master (v4).

**Comment by iMichka** [comment]
Ok thanks for the clarification. In that case we can close this issue.

Is there any EOL date for v3 / replacement date with v4 (if it is known)? Just to document this on our side.

**Comment by evoskuil** [comment]
No specific date.
