### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by MichielBruijn** [libbitcoin/libbitcoin-system#1238]
On linux mint I try to build libbitcoin with:
sudo ./install.sh --build-boost --disable-shared

But it ends with:
  CXXLD    src/libbitcoin-system.la
copying selected object files to avoid basename conflicts...
  CXXLD    examples/libbitcoin-system-examples
/usr/bin/ld: src/.libs/libbitcoin-system.so: undefined reference to `boost::re_detail_107200::put_mem_block(void*)'
/usr/bin/ld: src/.libs/libbitcoin-system.so: undefined reference to `boost::re_detail_107200::get_mem_block()'
/usr/bin/ld: src/.libs/libbitcoin-system.so: undefined reference to `boost::re_detail_107200::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
/usr/bin/ld: src/.libs/libbitcoin-system.so: undefined reference to `boost::re_detail_107200::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
/usr/bin/ld: src/.libs/libbitcoin-system.so: undefined reference to `boost::re_detail_107200::verify_options(unsigned int, boost::regex_constants::_match_flags)'
/usr/bin/ld: src/.libs/libbitcoin-system.so: undefined reference to `boost::re_detail_107200::get_default_error_string(boost::regex_constants::error_type)'
/usr/bin/ld: src/.libs/libbitcoin-system.so: undefined reference to `boost::re_detail_107200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
/usr/bin/ld: src/.libs/libbitcoin-system.so: undefined reference to `boost::re_detail_107200::raise_runtime_error(std::runtime_error const&)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:2498: examples/libbitcoin-system-examples] Error 1

What's wrong?

**Comment by evoskuil** [comment]
Looks like it’s missing boost regex.

**Comment by MichielBruijn** [comment]
When I use a prefix it's building.

**Comment by evoskuil** [comment]
Your OP showed a prefix, so I didn’t have an answer. But if you install without one you should expect problems, as libtool will grab your previously-installed boost, which doesn’t have the required boost regex component.

**Comment by evoskuil** [comment]
DLL Hell is as bad on Linux as it ever was on Windows.

**Comment by MichielBruijn** [comment]
> Your OP showed a prefix, so I didn’t have an answer. But if you install without one you should expect problems, as libtool will grab your previously-installed boost, which doesn’t have the required boost regex component.

Oops, my OP was wrong. I didn't use the prefix first time.

**Comment by evoskuil** [comment]
Closing as resolved.
