### ISSUE TITLE
Libbitcoin installation problem 

### ISSUE THREAD

**Issue by Jgroover100** [libbitcoin/libbitcoin-system#1245]
I have tried everything to install libbitcoin version 3. It keeps terminating before finishing.  I have everything installed new and am running the following command:
./install.sh --prefix=/me/libbitcoin/ --build-boost --disable-shared --with-ICU --build-ICU

Anyone have any idea of how to get this installed?

**Comment by evoskuil** [comment]
Error message?

**Comment by Jgroover100** [comment]
Lmmn caused process to terminate. Error 1.

I will double check the error. I should have written it down. I will the next time.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Jgroover100** [comment]
I finally got everything installed and working in regards to the bitcoin installation.
