### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Jgroover100** [libbitcoin/libbitcoin-system#1246]
After all the work I did in installing the libraries I am getting the following error when compiling my program.

Collect2: error: ld returned 1exit status

Does anyone have a fix or comments?

**Comment by Jgroover100** [comment]
Compilation terminated
/Use/lib/gcc/x86_64-linux-gnu/9/../../x86_64-linux-gnu/sert1.o: in function'_start': (.text+0x24): undefined reference to 'main'
Collect2: error:ld returned 1 exit status 

This is the error. Anybody with a solution? Thanks

**Comment by evoskuil** [comment]
That's not much to go on especially considering it's your (custom) project.

**Comment by Jgroover100** [comment]
I understand. The issue I believe is with the compiling options. I'm just trying a very simple program to get used to programming with the libbitcoin library.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by evoskuil** [comment]
The examples project is a very simple program that compiles with the libbitcoin-system library and is verified in CI.

**Comment by Jgroover100** [comment]
I have followed the instructions and that's the error I'm getting. Is it configuration or something else?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by evoskuil** [comment]
Impossible to say, I don't have your repro. But the examples project (and tests project) builds in CI on multiple platforms.

**Comment by Jgroover100** [comment]
Could it be that I am giving the wrong command options in the compiler?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by pmienk** [comment]
Closed as both stale and external.
