### ISSUE TITLE
Explain for stupid please how to compile on g ++?

### ISSUE THREAD

**Issue by golddunicorn** [libbitcoin/libbitcoin-system#1251]
I downloaded according to the instructions on Ubuntu 20.04 But now how to add include to g++ when I need: #include <bitcoin/bitcoin.hpp>

Error:

fatal error: bitcoin/bitcoin.hpp: No such file or directory
     | #include <bitcoin/bitcoin.hpp>

**Comment by evoskuil** [comment]
The include statement is correct, but presumes that relative include directories are configured. This is really more of a question for maintainers of your build system. You can also review our build configuration for the "examples" project, which links libbitcoin. You can always provide an explicit or build-relative path (in quotes).
