### ISSUE TITLE
apparently compiles on macOS but doesn't work

### ISSUE THREAD

**Issue by sinepgnol** [libbitcoin/libbitcoin-system#1252]
Hello,

please pardon my ignorance, but I am trying to compile the libbitcoin-system with ICU according to what it says in the notes for macOS. It finished apparently with no errors but trying to run the command `bx`, nothing happens.
Here is the output, I couldn't paste it here because it's too long: 
[output.txt](https://github.com/libbitcoin/libbitcoin-system/files/8599777/output.txt)

**Comment by evoskuil** [comment]
You compiled libbitcoin-system, not libbitcoin-explorer.
