### ISSUE TITLE
Remove dependency on libbboost

### ISSUE THREAD

**Issue by pantadeusz** [libbitcoin/libbitcoin-system#1262]
The boost library is a dependency that has to be in the correct version number, and compiling library on some distros requires building boost as well. I suggest to work on the replacing boost with C++17 or C++20 pieces wherever possible.

**Comment by evoskuil** [comment]
This has been done to a great extent in v4 (master, c++20), what remains is non-trivial to remove (asio and iostreams for example).

**Comment by evoskuil** [comment]
There are a couple areas remaining where this reduction is incomplete, notably regex. Pull requests welcome.
