### ISSUE TITLE
Question about c++17 git tag

### ISSUE THREAD

**Issue by chenrui333** [libbitcoin/libbitcoin-system#1301]
👋 it looks like there is [c++17 git tag](https://github.com/libbitcoin/libbitcoin-system/releases/tag/c%2B%2B17) in this repo, is that supposed to a release? Thanks!

![image](https://user-images.githubusercontent.com/1580956/212503110-7dd1df7f-a8e0-4c7c-b5a7-e5669491f7f5.png)

**Comment by evoskuil** [comment]
No, latest release is the version3 branch.
