### ISSUE TITLE
c++ builder

### ISSUE THREAD

**Issue by virus-cyber** [libbitcoin/libbitcoin-system#1336]
hello, how can I run C++ builder?

**Comment by evoskuil** [comment]
Please clarify.

**Comment by virus-cyber** [comment]
for C++ Builder there is only BOOST 1.7 in other cases there are many errors

**Comment by virus-cyber** [comment]
you can build in c++ builder

**Comment by evoskuil** [comment]
This is not a supported development environment. We provide CI builds in vc++, gcc, clang, and macOS clang, on Windows, Linux and macOS, for autotools, cmake, visual studio (and vs code). If you would like to work through issues with Builder we can help but more specifics are required than “many errors”.

**Comment by virus-cyber** [comment]
I'm trying to build this assembly since it has boost 1.72 https://github.com/libbitcoin/libbitcoin-system/tree/1e9760c4d6e5e0f15535c3c58867da91a44fb358
[bcc32c Error] constants.hpp(60): use of overloaded operator '==' is ambiguous (with operand types 'std::fpos<int>' and 'int')
  byte_reader.ipp(564): in instantiation of function template specialization 'libbitcoin::is_zero<std::fpos<int> >' requested here
  byte_reader.ipp(432): in instantiation of member function 'libbitcoin::system::byte_reader<std::basic_istream<char, std::char_traits<char> > >::seeker' requested here
  byte_reader.hpp(44): in instantiation of member function 'libbitcoin::system::byte_reader<std::basic_istream<char, std::char_traits<char> > >::do_skip_bytes' requested here
  block.cpp(93): in instantiation of member function 'libbitcoin::system::byte_reader<std::basic_istream<char, std::char_traits<char> > >::byte_reader' requested here
  iosfwd(101): candidate function
  iosfwd(96): candidate function
  constants.hpp(60): built-in candidate operator==(long long, int)
  constants.hpp(60): built-in candidate operator==(double, int)
  constants.hpp(60): built-in candidate operator==(long, int)
  constants.hpp(60): built-in candidate operator==(int, int)
  constants.hpp(60): built-in candidate operator==(__float128, int)
  constants.hpp(60): built-in candidate operator==(float, int)
  constants.hpp(60): built-in candidate operator==(long double, int)
  constants.hpp(60): built-in candidate operator==(long long, float)
  constants.hpp(60): built-in candidate operator==(long long, double)
  constants.hpp(60): built-in candidate operator==(long long, long double)
  constants.hpp(60): built-in candidate operator==(long long, __float128)
  constants.hpp(60): built-in candidate operator==(long long, long)
  constants.hpp(60): built-in candidate operator==(long long, long long)
  constants.hpp(60): built-in candidate operator==(long long, __int128)
  constants.hpp(60): built-in candidate operator==(long long, unsigned int)
  constants.hpp(60): built-in candidate operator==(long long, unsigned long)
  constants.hpp(60): built-in candidate operator==(long long, unsigned long long)
  constants.hpp(60): built-in candidate operator==(long long, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(__int128, int)
  constants.hpp(60): built-in candidate operator==(unsigned int, int)
  constants.hpp(60): built-in candidate operator==(unsigned long, int)
  constants.hpp(60): built-in candidate operator==(unsigned long long, int)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, int)
  constants.hpp(60): built-in candidate operator==(double, __int128)
  constants.hpp(60): built-in candidate operator==(double, unsigned int)
  constants.hpp(60): built-in candidate operator==(double, unsigned long)
  constants.hpp(60): built-in candidate operator==(double, unsigned long long)
  constants.hpp(60): built-in candidate operator==(double, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(long double, float)
  constants.hpp(60): built-in candidate operator==(long double, double)
  constants.hpp(60): built-in candidate operator==(long double, long double)
  constants.hpp(60): built-in candidate operator==(long double, __float128)
  constants.hpp(60): built-in candidate operator==(long double, long)
  constants.hpp(60): built-in candidate operator==(long double, long long)
  constants.hpp(60): built-in candidate operator==(long double, __int128)
  constants.hpp(60): built-in candidate operator==(long double, unsigned int)
  constants.hpp(60): built-in candidate operator==(long double, unsigned long)
  constants.hpp(60): built-in candidate operator==(long double, unsigned long long)
  constants.hpp(60): built-in candidate operator==(long double, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(__float128, float)
  constants.hpp(60): built-in candidate operator==(__float128, double)
  constants.hpp(60): built-in candidate operator==(__float128, long double)
  constants.hpp(60): built-in candidate operator==(__float128, __float128)
  constants.hpp(60): built-in candidate operator==(__float128, long)
  constants.hpp(60): built-in candidate operator==(__float128, long long)
  constants.hpp(60): built-in candidate operator==(__float128, __int128)
  constants.hpp(60): built-in candidate operator==(__float128, unsigned int)
  constants.hpp(60): built-in candidate operator==(__float128, unsigned long)
  constants.hpp(60): built-in candidate operator==(__float128, unsigned long long)
  constants.hpp(60): built-in candidate operator==(__float128, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(int, float)
  constants.hpp(60): built-in candidate operator==(int, double)
  constants.hpp(60): built-in candidate operator==(int, long double)
  constants.hpp(60): built-in candidate operator==(int, __float128)
  constants.hpp(60): built-in candidate operator==(int, long)
  constants.hpp(60): built-in candidate operator==(int, long long)
  constants.hpp(60): built-in candidate operator==(int, __int128)
  constants.hpp(60): built-in candidate operator==(int, unsigned int)
  constants.hpp(60): built-in candidate operator==(int, unsigned long)
  constants.hpp(60): built-in candidate operator==(int, unsigned long long)
  constants.hpp(60): built-in candidate operator==(int, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(long, float)
  constants.hpp(60): built-in candidate operator==(long, double)
  constants.hpp(60): built-in candidate operator==(long, long double)
  constants.hpp(60): built-in candidate operator==(long, __float128)
  constants.hpp(60): built-in candidate operator==(long, long)
  constants.hpp(60): built-in candidate operator==(long, long long)
  constants.hpp(60): built-in candidate operator==(long, __int128)
  constants.hpp(60): built-in candidate operator==(long, unsigned int)
  constants.hpp(60): built-in candidate operator==(long, unsigned long)
  constants.hpp(60): built-in candidate operator==(long, unsigned long long)
  constants.hpp(60): built-in candidate operator==(long, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(float, float)
  constants.hpp(60): built-in candidate operator==(float, double)
  constants.hpp(60): built-in candidate operator==(float, long double)
  constants.hpp(60): built-in candidate operator==(float, __float128)
  constants.hpp(60): built-in candidate operator==(float, long)
  constants.hpp(60): built-in candidate operator==(float, long long)
  constants.hpp(60): built-in candidate operator==(float, __int128)
  constants.hpp(60): built-in candidate operator==(float, unsigned int)
  constants.hpp(60): built-in candidate operator==(float, unsigned long)
  constants.hpp(60): built-in candidate operator==(float, unsigned long long)
  constants.hpp(60): built-in candidate operator==(float, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(double, float)
  constants.hpp(60): built-in candidate operator==(__int128, float)
  constants.hpp(60): built-in candidate operator==(__int128, double)
  constants.hpp(60): built-in candidate operator==(__int128, long double)
  constants.hpp(60): built-in candidate operator==(__int128, __float128)
  constants.hpp(60): built-in candidate operator==(double, double)
  constants.hpp(60): built-in candidate operator==(__int128, long)
  constants.hpp(60): built-in candidate operator==(__int128, long long)
  constants.hpp(60): built-in candidate operator==(__int128, __int128)
  constants.hpp(60): built-in candidate operator==(__int128, unsigned int)
  constants.hpp(60): built-in candidate operator==(__int128, unsigned long)
  constants.hpp(60): built-in candidate operator==(__int128, unsigned long long)
  constants.hpp(60): built-in candidate operator==(__int128, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(unsigned int, float)
  constants.hpp(60): built-in candidate operator==(unsigned int, double)
  constants.hpp(60): built-in candidate operator==(unsigned int, long double)
  constants.hpp(60): built-in candidate operator==(unsigned int, __float128)
  constants.hpp(60): built-in candidate operator==(double, long double)
  constants.hpp(60): built-in candidate operator==(unsigned int, long)
  constants.hpp(60): built-in candidate operator==(unsigned int, long long)
  constants.hpp(60): built-in candidate operator==(unsigned int, __int128)
  constants.hpp(60): built-in candidate operator==(unsigned int, unsigned int)
  constants.hpp(60): built-in candidate operator==(unsigned int, unsigned long)
  constants.hpp(60): built-in candidate operator==(unsigned int, unsigned long long)
  constants.hpp(60): built-in candidate operator==(unsigned int, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(unsigned long, float)
  constants.hpp(60): built-in candidate operator==(unsigned long, double)
  constants.hpp(60): built-in candidate operator==(unsigned long, long double)
  constants.hpp(60): built-in candidate operator==(unsigned long, __float128)
  constants.hpp(60): built-in candidate operator==(double, __float128)
  constants.hpp(60): built-in candidate operator==(unsigned long, long)
  constants.hpp(60): built-in candidate operator==(unsigned long, long long)
  constants.hpp(60): built-in candidate operator==(unsigned long, __int128)
  constants.hpp(60): built-in candidate operator==(unsigned long, unsigned int)
  constants.hpp(60): built-in candidate operator==(unsigned long, unsigned long)
  constants.hpp(60): built-in candidate operator==(unsigned long, unsigned long long)
  constants.hpp(60): built-in candidate operator==(unsigned long, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(unsigned long long, float)
  constants.hpp(60): built-in candidate operator==(unsigned long long, double)
  constants.hpp(60): built-in candidate operator==(unsigned long long, long double)
  constants.hpp(60): built-in candidate operator==(unsigned long long, __float128)
  constants.hpp(60): built-in candidate operator==(double, long)
  constants.hpp(60): built-in candidate operator==(unsigned long long, long)
  constants.hpp(60): built-in candidate operator==(unsigned long long, long long)
  constants.hpp(60): built-in candidate operator==(unsigned long long, __int128)
  constants.hpp(60): built-in candidate operator==(unsigned long long, unsigned int)
  constants.hpp(60): built-in candidate operator==(unsigned long long, unsigned long)
  constants.hpp(60): built-in candidate operator==(unsigned long long, unsigned long long)
  constants.hpp(60): built-in candidate operator==(unsigned long long, unsigned __int128)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, float)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, double)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, long double)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, __float128)
  constants.hpp(60): built-in candidate operator==(double, long long)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, long)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, long long)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, __int128)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, unsigned int)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, unsigned long)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, unsigned long long)
  constants.hpp(60): built-in candidate operator==(unsigned __int128, unsigned __int128)

**Comment by evoskuil** [comment]
None of the line numbers make sense with the build errors. Are you building latest code?

**Comment by virus-cyber** [comment]
sorry this compilation
https://github.com/libbitcoin/libbitcoin-system/blob/fee9695ce95b554ba1e67b3ded0c849d0f073807/include/bitcoin/system/constraints.hpp

**Comment by pmienk** [comment]
@virus-cyber as there has not been movement on this topic, I would like to clarify my understanding of your issue. It seems from the above that you are attempting to use an unverified toolchain. You multiply mention boost, indicating that your environment has version 1.7. Are you aware that, depending on the branch of libbitcoin a minimum required version of boost is 1.72 to 1.76? It should also be noted that version 1.80 has breaking changes.

I am unaware of c++ builder details, does this toolchain enforce the restrictions on boost or other dependencies expressed in either autotools or cmake? If not then you will need to do so yourself or in whatever method works in that environment.

If I am mistaken above, please provide correction and additional details.

**Comment by virus-cyber** [comment]
hello, how did you get the idea that it’s impossible to collect for boost 1.70
just built https://github.com/libbitcoin/libbitcoin-system/tree/version3 on boost 1.70
c++ builder is almost ready to be assembled before replacing _MSC_VER with __BORLANDC__ everywhere
