### ISSUE TITLE
Boost 1.76.0 or later is required but was not found.

### ISSUE THREAD

**Issue by sssergy** [libbitcoin/libbitcoin-system#1358]
Ubuntu 20.04.4 LTS
Install scrypt latest. Command ./install.sh --prefix=/usr/local --with-icu --build-icu --build-boost --disable-shared
![image](https://user-images.githubusercontent.com/26333870/233366871-db2a5d8b-bb2a-454a-b612-29684858c765.png)

**Comment by evoskuil** [comment]
Hello, please provide the full log, not just a screenshot of the last page. Thanks

**Comment by sssergy** [comment]
I figured out the boost, but now there is another error.
[config.log](https://github.com/libbitcoin/libbitcoin-system/files/11286533/config.log)
[install_sh.log](https://github.com/libbitcoin/libbitcoin-system/files/11286534/install_sh.log)

**Comment by sssergy** [comment]
Issue resolved by replacing boost version 1.72 with version 1.78
