### ISSUE TITLE
CLang14: warning: double slash removed.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-system#1385]
```
ld: warning: double slash removed from -install_name (/Users/runner/work/libbitcoin-system//prefix/lib/libsecp256k1.0.dylib)
```
https://github.com/libbitcoin/libbitcoin-system/actions/runs/7699725426/job/20981991442?pr=1378#step:8:627

**Comment by pmienk** [comment]
Was addressed in previous pull request and fix was previously integrated into [libbitcoin-build](https://github.com/libbitcoin/libbitcoin-build/commit/a3f48498786fd0b18b5b12199e4182a79e256224)
