### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by alonargel** [libbitcoin/libbitcoin-system#1398]
Version 3.8.0 does not compile in vs 2022, there are a lot of boost errors. While from Master branch it compiles perfectly. But in master branch, it’s as if all the necessary methods have been cut out; I can’t even create the create_mnemonic method. How to solve a problem?
![Снимок экрана 2024-02-17 020743](https://github.com/libbitcoin/libbitcoin-system/assets/160269798/f262d203-06d9-40cf-80f8-bb5f13b41f6d)

**Comment by evoskuil** [comment]
While not released, v4 (master) is production quality in the system repo and has all of the functionality and more than v3. Much has be restructured and renamed however.

**Comment by evoskuil** [comment]
[BIP39 mnemonics](https://github.com/libbitcoin/libbitcoin-system/blob/master/include/bitcoin/system/wallet/mnemonics/mnemonic.hpp)

**Comment by alonargel** [comment]
> While not released, v4 (master) is production quality in the system repo and has all of the functionality and more than v3. Much has been restructured and renamed however.

Ok, can you give me an example of how to get a Bitcoin address from a mnemonic? I tried to do this and get the master key, but it doesn't work any further. None of the examples from the libbitcoin wiki work.

#include <cstdlib>
#include <string>
#include <bitcoin/system.hpp>

BC_USE_LIBBITCOIN_MAIN
LIBBITCOIN_SYSTEM_WALLET_MNEMONICS_MNEMONIC_HPP

int bc::system::main(int argc, char* argv[])
{
    using namespace bc;
    using namespace bc::system;
    using namespace bc::system::wallet;

    std::string mnemonic_phrase = "bunker churn kangaroo melt bleak chalk vacant alert reason exit forward language";
    libbitcoin::system::wallet::mnemonic mnemonic(mnemonic_phrase);

    libbitcoin::system::wallet::hd_private key = mnemonic.to_key();
    system::cout << mnemonic.to_key() << std::endl;

    return 0;
}

**Comment by evoskuil** [comment]
Closing this issue as not supported (vs2022/v3). See https://github.com/libbitcoin/libbitcoin-system/issues/1399

**Comment by pmienk** [comment]
Please provide any specifics as to project compilation failures. Github actions currently shows vs2022 sln and proj files compiling successfully.

**Comment by pmienk** [comment]
Closing in the absence of details.
