### ISSUE TITLE
Adding libbitcoin-system to Conan package manager

### ISSUE THREAD

**Issue by hllcg** [libbitcoin/libbitcoin-system#1402]
I'm proposing to include libbitcoin in the Conan. This would simplify managing dependencies for Bitcoin-related projects, enhancing development efficiency. Your thoughts on this would be greatly appreciated.
Thanks in advance

**Comment by evoskuil** [comment]
System v4 (master) is not released, though it could be considered production quality. V3 is mature but getting a little long in the tooth.

**Comment by OnurDemirgoz** [comment]
Hello @evoskuil is that means will it be in conan with the release and when will it be?
Thanks for the help.

**Comment by evoskuil** [comment]
No, we don’t maintain external distributions. Others have done so in the past and you are welcome to do so.
