### ISSUE TITLE
I need an updated example.

### ISSUE THREAD

**Issue by Z-fly** [libbitcoin/libbitcoin-system#1438]
https://github.com/libbitcoin/libbitcoin-system/wiki/Examples-from-Addresses-and-HD-Wallets
The code on this page is not compatible with https://github.com/libbitcoin/libbitcoin-system/tree/version3 
please update the code.

**Comment by evoskuil** [comment]
If there is a build break feel free to post it.

**Comment by Z-fly** [comment]
@evoskuil How to fix it?  https://github.com/libbitcoin/libbitcoin-system/issues/1354#issuecomment-1503046751
![image](https://github.com/libbitcoin/libbitcoin-system/assets/10470892/1d0f0be9-260f-4f6e-9864-5c07c18a9977)
Now I use /version3.
I'm very sorry, I'm a beginner in C++.

**Comment by evoskuil** [comment]
It looks like you are writing version4 code with a version3 dependency. The namespace organizations are different.

**Comment by evoskuil** [comment]
If you are only working with libbitcoin-system I recommends version4 (master). But if you need bx then you need to use version3, because it’s not buildable yet in master.
