### ISSUE TITLE
Wiki page refers to non-existing functions

### ISSUE THREAD

**Issue by pavolkacej** [libbitcoin/libbitcoin-system#1532]
Following the wiki example https://github.com/libbitcoin/libbitcoin-system/wiki/Addresses-and-HD-Wallets, the `base16_literal` and `extend_data` are not being found in the environment. Is it possible to update the wiki page?

**Comment by evoskuil** [comment]
Hello, are you using the /master branch? Master is staging for v4, /version3 is the current released code and should be consistent with documentation.

**Comment by pavolkacej** [comment]
Hi @evoskuil. you are right, I used master branch. After moving to v3.8.0, the code is consistent with the wiki page. Thank you very much!
