### ISSUE TITLE
Rename libbitcoin to libbitcoin-system.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-system#311]
Libbitcoin is no longer a prerequisite for all other libraries, so the rationale for naming it accordingly no longer holds. The asymmetry also requires special-casing in the build system.. This is a change that @genjix suggested about a year ago.

**Comment by RojavaCrypto** [comment]
Yes, maybe we can do this now, keep the libbitcoin repo for old builds but mark it as obsolete. libbitcoin-system is a better description.

**Comment by RojavaCrypto** [comment]
What's the plan with this? Do you want me to make the necessary updates?

We can add a special configure message to this repo saying that this is deprecated and people should use libbitcoin_system repo instead. We should continue pushing to both this and libbitcoin_system repo up until v3 release.

**Comment by evoskuil** [comment]
My plan is to retain this repo for 3.0, which is close to release, and fork off the new one for 4.0.

**Comment by evoskuil** [comment]
This is deferred until we have code generation for VS projects (too many changes otherwise).

**Comment by evoskuil** [comment]
Code generation for VS projects has been implemented by @pmienk so this should fall into place for v4.

**Comment by evoskuil** [comment]
@pmienk could you tackle this one in master? Need to knock down a few issues in libbitcoin.

**Comment by evoskuil** [comment]
We will need to either retain the libbitcoin repo for previous version builds, as described above, or apply the change to version3 as well (and drop version2). We’d still want to retain the libbitcoin repo, for the wiki links at least, and can use it as the home for things general, including the website (eventually).

**Comment by evoskuil** [comment]
Yes, I’d like to get full consistency so that libbitcoin-system is no longer a special case.

We can retain the bc:: alias as bitcoin::system::

**Comment by evoskuil** [comment]
Complete.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-system/pull/1088
