### ISSUE TITLE
Boost Log rotation may throw `boost::filesystem::filesystem_error`

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-system#766]
This issue appears to be internal to boost::log.
```
terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::last_write_time: No such file or directory:
```

**Comment by evoskuil** [comment]
Saw this is in v3.1 binaries while release smoke testing BS on Ubuntu and BN on macOS. Presumably this is a boost issue on *nix and is showing up now because log rotation is enabled by default.

**Comment by aaronovz1** [comment]
This is still an issue in Boost 1.67.

**Comment by evoskuil** [comment]
log moved to network, boost log removed.
